-----BEGIN-----
-----SETTINGS-----
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:10.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.05
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:10000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:50
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:0.5
CONFIDENCE_THRESHOLD:0.1
CONFIDENCE_ADAPTIVE:True
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:True
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=100000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3203518/1690967881_461694253', seed=42, img_per_thread=5555)
will save 100000 patches in /scratch-local/sunnys.3203518/1690967881_461694253/single_img_crops/crops
100000 took 1.01min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-02 11:19:20,008 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-02 11:19:20,008 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3203518/1690967881_461694253/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3203518/1690967881_461694253/cifar-10-python.tar.gz to /scratch-local/sunnys.3203518/1690967881_461694253
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=10.0, 10 classes): [259 271 116 269 240 311 223 239 284 288]
INFO flwr 2023-08-02 11:24:02,683 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-02 11:24:05,567	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8266 [39m[22m
INFO flwr 2023-08-02 11:24:06,543 | app.py:179 | Flower VCE: Ray initialized with resources: {'CPU': 18.0, 'object_store_memory': 61847529062.0, 'GPU': 1.0, 'node:145.136.62.63': 1.0, 'memory': 103079215104.0, 'accelerator_type:A100': 1.0}
INFO flwr 2023-08-02 11:24:06,544 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-02 11:24:06,544 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-02 11:24:06,544 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-02 11:24:12,647 | server.py:91 | initial parameters (loss, other metrics): 2.3234217651367186, {'server_test_acc': 0.108}
INFO flwr 2023-08-02 11:24:12,647 | server.py:101 | FL starting
DEBUG flwr 2023-08-02 11:24:21,600 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3510245)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3510250)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:25:10,729 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-02 11:25:10,940 | fed_df.py:351 | Warm start at round 1
[2m[36m(launch_and_fit pid=3510247)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:25:11,053 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3510245)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3510244)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3510246)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3510247)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3510248)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3510250)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3510249)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3510251)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3510251)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3510248)[0m malloc_consolidate(): invalid chunk size
E0802 11:25:11.308791224 3507219 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=3510249)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3510244)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3510246)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:25:46,715 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:25:46,716 | fed_df.py:523 | Average fusion training loss : 0.4935324908494949, val accuracy : 0.28804, best val accuracy : 0.3162
Average local training loss : 9.488184297084807
Average local training accuracy : 0.3171111111111111
INFO flwr 2023-08-02 11:25:47,920 | server.py:116 | fit progress: (1, 3.7691418701171875, {'server_test_acc': 0.3041}, 95.27255112188868)
INFO flwr 2023-08-02 11:25:47,920 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-02 11:25:57,154 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-02 11:26:46,796 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-02 11:26:47,009 | fed_df.py:351 | Warm start at round 2
INFO flwr 2023-08-02 11:26:47,121 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3640075)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3640077)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3640074)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3640078)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3640080)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3640079)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3640081)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3640082)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3640080)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3640079)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3640081)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3640077)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3640074)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3640082)[0m malloc_consolidate(): invalid chunk size
E0802 11:26:49.365030513 3604475 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=3640078)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:27:21,974 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:27:21,975 | fed_df.py:523 | Average fusion training loss : 0.4342612875699997, val accuracy : 0.38103999999999993, best val accuracy : 0.3902
Average local training loss : 8.37350966706872
Average local training accuracy : 0.4229305555555555
INFO flwr 2023-08-02 11:27:23,210 | server.py:116 | fit progress: (2, 3.7104874877929688, {'server_test_acc': 0.3992}, 190.5629662689753)
INFO flwr 2023-08-02 11:27:23,210 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-02 11:27:32,673 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3788832)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3788837)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:28:20,842 | server.py:229 | fit_round 3 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3788829)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:28:21,056 | fed_df.py:351 | Warm start at round 3
[2m[36m(launch_and_fit pid=3788831)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-08-02 11:28:21,168 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3788829)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3788831)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3788832)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3788835)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3788837)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3788834)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3788836)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3788833)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3788836)[0m malloc_consolidate(): invalid chunk size
E0802 11:28:22.060233547 3731889 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=3788835)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3788834)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3788833)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:28:56,128 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:28:56,129 | fed_df.py:523 | Average fusion training loss : 0.23018339228630066, val accuracy : 0.5075999999999999, best val accuracy : 0.5164
Average local training loss : 7.17678505629301
Average local training accuracy : 0.55365
INFO flwr 2023-08-02 11:28:57,375 | server.py:116 | fit progress: (3, 1.9877834533691405, {'server_test_acc': 0.522}, 284.7278411788866)
INFO flwr 2023-08-02 11:28:57,375 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-02 11:29:06,881 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-02 11:29:54,592 | server.py:229 | fit_round 4 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3925378)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:29:54,809 | fed_df.py:351 | Warm start at round 4
INFO flwr 2023-08-02 11:29:54,951 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3925377)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3925376)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3925378)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3925448)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3925446)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3925447)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3925449)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3925450)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3925376)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3925448)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3925450)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3925447)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3925446)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3925377)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3925449)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:30:29,621 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:30:29,621 | fed_df.py:523 | Average fusion training loss : 0.15131158405542375, val accuracy : 0.58076, best val accuracy : 0.5866
Average local training loss : 6.115146815031766
Average local training accuracy : 0.6632972222222222
INFO flwr 2023-08-02 11:30:30,857 | server.py:116 | fit progress: (4, 1.4462037994384767, {'server_test_acc': 0.5876}, 378.2104105739854)
INFO flwr 2023-08-02 11:30:30,858 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-02 11:30:40,418 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4044176)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4044177)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:31:29,222 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-02 11:31:29,437 | fed_df.py:351 | Warm start at round 5
[2m[36m(launch_and_fit pid=4044169)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4044174)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:31:29,550 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4044169)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4044172)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4044176)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4044173)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4044168)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4044034)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4044174)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4044177)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4044168)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4044172)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4044034)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4044173)[0m malloc_consolidate(): invalid chunk size
E0802 11:31:33.200054440 4037236 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-02 11:32:02,228 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:32:02,228 | fed_df.py:523 | Average fusion training loss : 0.0710244041979313, val accuracy : 0.64744, best val accuracy : 0.6504
Average local training loss : 5.7565032307058575
Average local training accuracy : 0.6991611111111111
INFO flwr 2023-08-02 11:32:03,451 | server.py:116 | fit progress: (5, 1.2386199401855469, {'server_test_acc': 0.6376}, 470.8036533619743)
INFO flwr 2023-08-02 11:32:03,451 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-02 11:32:13,096 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-02 11:33:03,149 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-02 11:33:03,363 | fed_df.py:351 | Warm start at round 6
INFO flwr 2023-08-02 11:33:03,506 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4139133)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4139135)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4139143)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4139145)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4139146)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4139144)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4139147)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4139148)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4139133)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4139145)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4139147)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4139144)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4139146)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4139135)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4139143)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4139148)[0m malloc_consolidate(): invalid chunk size
E0802 11:33:05.569785099 4111935 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-08-02 11:33:35,637 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:33:35,638 | fed_df.py:523 | Average fusion training loss : 0.0668507407605648, val accuracy : 0.6610400000000001, best val accuracy : 0.668
Average local training loss : 5.199332527443767
Average local training accuracy : 0.7585805555555556
INFO flwr 2023-08-02 11:33:36,845 | server.py:116 | fit progress: (6, 1.2686992126464844, {'server_test_acc': 0.6632}, 564.1975430410821)
INFO flwr 2023-08-02 11:33:36,845 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-02 11:33:46,407 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=82733)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=82877)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=82736)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:34:34,699 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-02 11:34:34,914 | fed_df.py:351 | Warm start at round 7
INFO flwr 2023-08-02 11:34:35,056 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=82733)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=82877)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=82737)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=82807)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=82808)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=82736)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=82876)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=82806)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=82808)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=82876)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=82806)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=82807)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=82737)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 11:35:07,800 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:35:07,800 | fed_df.py:523 | Average fusion training loss : 0.04511419110000134, val accuracy : 0.67196, best val accuracy : 0.6788
Average local training loss : 4.909855203330516
Average local training accuracy : 0.788125
INFO flwr 2023-08-02 11:35:09,039 | server.py:116 | fit progress: (7, 1.2843581481933595, {'server_test_acc': 0.6755}, 656.3920740298927)
INFO flwr 2023-08-02 11:35:09,039 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-02 11:35:18,626 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-02 11:36:09,355 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-02 11:36:09,570 | fed_df.py:351 | Warm start at round 8
[2m[36m(launch_and_fit pid=186024)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=186030)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=186297)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:36:09,682 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=186024)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=186030)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=186022)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=186297)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=186161)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=186296)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=186275)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=186162)[0m Fitting Client 12
E0802 11:36:10.411206339   28243 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=186275)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=186296)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=186162)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=186022)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=186161)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:36:41,389 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:36:41,389 | fed_df.py:523 | Average fusion training loss : 0.049469182156026366, val accuracy : 0.6954, best val accuracy : 0.6998
Average local training loss : 4.814960382506251
Average local training accuracy : 0.7984611111111112
INFO flwr 2023-08-02 11:36:42,589 | server.py:116 | fit progress: (8, 1.1879063385009765, {'server_test_acc': 0.6907}, 749.9417754400056)
INFO flwr 2023-08-02 11:36:42,589 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-02 11:36:51,811 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=286358)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:37:39,325 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-02 11:37:39,541 | fed_df.py:351 | Warm start at round 9
INFO flwr 2023-08-02 11:37:39,654 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=286358)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=286362)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=286363)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=286360)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=286379)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=286376)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=286377)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=286378)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=286379)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=286376)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=286362)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=286363)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=286360)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=286378)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=286377)[0m malloc_consolidate(): invalid chunk size
E0802 11:37:41.840330830  255342 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-08-02 11:38:11,653 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:38:11,653 | fed_df.py:523 | Average fusion training loss : 0.05752670157700777, val accuracy : 0.6961600000000001, best val accuracy : 0.702
Average local training loss : 4.733335237577557
Average local training accuracy : 0.8083750000000001
INFO flwr 2023-08-02 11:38:12,867 | server.py:116 | fit progress: (9, 1.3039254455566407, {'server_test_acc': 0.6927}, 840.2197972740978)
INFO flwr 2023-08-02 11:38:12,867 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-02 11:38:22,176 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-02 11:39:10,304 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-02 11:39:10,521 | fed_df.py:351 | Warm start at round 10
INFO flwr 2023-08-02 11:39:10,634 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=384702)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=384701)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=384705)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=384700)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=384706)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=384707)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=384704)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=384703)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=384705)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=384702)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=384704)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=384700)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=384706)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=384707)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=384701)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=384703)[0m double free or corruption (fasttop)
E0802 11:39:14.343095728  348204 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-08-02 11:39:42,724 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:39:42,724 | fed_df.py:523 | Average fusion training loss : 0.04658036808669567, val accuracy : 0.69992, best val accuracy : 0.7076
Average local training loss : 4.500859831646085
Average local training accuracy : 0.8314138888888889
INFO flwr 2023-08-02 11:39:43,937 | server.py:116 | fit progress: (10, 1.2950278350830078, {'server_test_acc': 0.704}, 931.2897488870658)
INFO flwr 2023-08-02 11:39:43,937 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-02 11:39:53,391 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=475422)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=475558)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=475695)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:40:45,194 | server.py:229 | fit_round 11 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=475692)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:40:45,412 | fed_df.py:351 | Warm start at round 11
INFO flwr 2023-08-02 11:40:45,524 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=475422)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=475558)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=475695)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=475692)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=475559)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=475693)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=475694)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=475696)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=475696)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=475693)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=475694)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=475559)[0m double free or corruption (fasttop)
E0802 11:40:49.628557751  562912 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-08-02 11:41:18,370 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:41:18,371 | fed_df.py:523 | Average fusion training loss : 0.05288708488643169, val accuracy : 0.7058, best val accuracy : 0.7124
Average local training loss : 4.365936374664306
Average local training accuracy : 0.8470888888888889
INFO flwr 2023-08-02 11:41:19,609 | server.py:116 | fit progress: (11, 1.2979467559814453, {'server_test_acc': 0.7099}, 1026.961699014064)
INFO flwr 2023-08-02 11:41:19,609 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-02 11:41:28,907 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-02 11:42:16,688 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-02 11:42:16,906 | fed_df.py:351 | Warm start at round 12
[2m[36m(launch_and_fit pid=612508)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:42:17,021 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=612508)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=612510)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=612579)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=612511)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=612583)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=612581)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=612582)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=612580)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=612511)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=612581)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=612579)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=612582)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=612583)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=612580)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=612510)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 11:42:50,440 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:42:50,440 | fed_df.py:523 | Average fusion training loss : 0.059153227165341375, val accuracy : 0.70924, best val accuracy : 0.7196
Average local training loss : 4.2109247975051405
Average local training accuracy : 0.8619277777777777
INFO flwr 2023-08-02 11:42:51,755 | server.py:116 | fit progress: (12, 1.2877573364257813, {'server_test_acc': 0.7212}, 1119.1078920729924)
INFO flwr 2023-08-02 11:42:51,755 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-02 11:43:01,226 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=734109)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=734114)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=734119)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=734115)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:43:51,829 | server.py:229 | fit_round 13 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=734120)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 11:43:52,046 | fed_df.py:351 | Warm start at round 13
INFO flwr 2023-08-02 11:43:52,157 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=734109)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=734114)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=734115)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=734120)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=734119)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=734118)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=734117)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=734116)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=734117)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=734118)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=734116)[0m corrupted size vs. prev_size in fastbins
E0802 11:43:55.210015247  564935 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
E0802 11:43:55.210093459  564935 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
E0802 11:43:55.210106055  564935 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
INFO flwr 2023-08-02 11:44:25,200 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:44:25,201 | fed_df.py:523 | Average fusion training loss : 0.05863687539100647, val accuracy : 0.71624, best val accuracy : 0.7256
Average local training loss : 4.2346188925206665
Average local training accuracy : 0.8590694444444446
INFO flwr 2023-08-02 11:44:26,405 | server.py:116 | fit progress: (13, 1.2806775909423829, {'server_test_acc': 0.722}, 1213.7576240219641)
INFO flwr 2023-08-02 11:44:26,405 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-02 11:44:35,640 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-02 11:45:22,848 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-02 11:45:23,063 | fed_df.py:351 | Warm start at round 14
INFO flwr 2023-08-02 11:45:23,176 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=859043)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=859044)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=859047)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=859048)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=859049)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=859051)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=859050)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=859052)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=859048)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=859043)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=859050)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=859047)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=859049)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=859044)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=859052)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=859051)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:45:55,322 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:45:55,322 | fed_df.py:523 | Average fusion training loss : 0.07985875825583935, val accuracy : 0.71376, best val accuracy : 0.722
Average local training loss : 4.012794759497047
Average local training accuracy : 0.878788888888889
INFO flwr 2023-08-02 11:45:56,527 | server.py:116 | fit progress: (14, 1.2081013366699218, {'server_test_acc': 0.7355}, 1303.880079926923)
INFO flwr 2023-08-02 11:45:56,527 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-02 11:46:05,823 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=949219)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-02 11:46:54,177 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-02 11:46:54,393 | fed_df.py:351 | Warm start at round 15
INFO flwr 2023-08-02 11:46:54,507 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=949219)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=949222)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=949223)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=949225)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=949224)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=949226)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=949228)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=949227)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=949223)[0m malloc_consolidate(): invalid chunk size
E0802 11:46:54.920415684 1008854 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=949225)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=949224)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=949228)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=949227)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=949226)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:47:29,133 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:47:29,134 | fed_df.py:523 | Average fusion training loss : 0.0869665720909834, val accuracy : 0.73124, best val accuracy : 0.7416
Average local training loss : 4.092041653394699
Average local training accuracy : 0.8696444444444444
INFO flwr 2023-08-02 11:47:30,350 | server.py:116 | fit progress: (15, 1.1851177520751952, {'server_test_acc': 0.735}, 1397.7034352619667)
INFO flwr 2023-08-02 11:47:30,351 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-02 11:47:40,038 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1061275)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1061271)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:48:29,860 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-02 11:48:30,076 | fed_df.py:351 | Warm start at round 16
INFO flwr 2023-08-02 11:48:30,189 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1061273)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1061275)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1061278)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1061409)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1061277)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1061271)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1061276)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1061410)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1061276)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1061278)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1061409)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1061273)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1061410)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1061277)[0m malloc_consolidate(): invalid chunk size
E0802 11:48:32.328298632 1132209 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
INFO flwr 2023-08-02 11:49:01,544 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:49:01,545 | fed_df.py:523 | Average fusion training loss : 0.09774905788898468, val accuracy : 0.7156800000000001, best val accuracy : 0.7206
Average local training loss : 3.8533028993755583
Average local training accuracy : 0.8923666666666666
INFO flwr 2023-08-02 11:49:02,759 | server.py:116 | fit progress: (16, 1.278918194580078, {'server_test_acc': 0.7228}, 1490.1115669019055)
INFO flwr 2023-08-02 11:49:02,759 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-02 11:49:12,061 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1156890)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:49:59,663 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-02 11:49:59,880 | fed_df.py:351 | Warm start at round 17
INFO flwr 2023-08-02 11:49:59,993 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1156890)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1156893)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1156891)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1156895)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1156892)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1156894)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1156896)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1156897)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1156896)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1156892)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1156894)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1156897)[0m double free or corruption (fasttop)
E0802 11:50:01.171855730 1132731 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=1156893)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1156895)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 11:50:31,283 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:50:31,284 | fed_df.py:523 | Average fusion training loss : 0.07046612995862961, val accuracy : 0.71076, best val accuracy : 0.716
Average local training loss : 3.795113308355212
Average local training accuracy : 0.8971333333333333
INFO flwr 2023-08-02 11:50:32,508 | server.py:116 | fit progress: (17, 1.38278583984375, {'server_test_acc': 0.7176}, 1579.8609613329172)
INFO flwr 2023-08-02 11:50:32,508 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-02 11:50:41,891 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1229961)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-02 11:51:29,274 | server.py:229 | fit_round 18 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1229960)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1229946)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:51:29,493 | fed_df.py:351 | Warm start at round 18
INFO flwr 2023-08-02 11:51:29,660 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1229946)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1229947)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1229950)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1229952)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1229953)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1229962)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1229960)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1229961)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1229947)[0m double free or corruption (fasttop)
E0802 11:51:30.201736944 1205004 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=1229950)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1229962)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1229952)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1229953)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 11:52:01,196 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:52:01,197 | fed_df.py:523 | Average fusion training loss : 0.08743724516034126, val accuracy : 0.72688, best val accuracy : 0.738
Average local training loss : 3.8923753939568995
Average local training accuracy : 0.8902499999999999
INFO flwr 2023-08-02 11:52:02,412 | server.py:116 | fit progress: (18, 1.3021061767578126, {'server_test_acc': 0.7384}, 1669.7653972350527)
INFO flwr 2023-08-02 11:52:02,413 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-02 11:52:11,788 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-02 11:52:59,005 | server.py:229 | fit_round 19 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1302857)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:52:59,222 | fed_df.py:351 | Warm start at round 19
INFO flwr 2023-08-02 11:52:59,334 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1302857)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1302858)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1302856)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1302860)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1302859)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1302861)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1302863)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1302862)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1302858)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1302859)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1302863)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1302856)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1302860)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1302862)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1302861)[0m malloc_consolidate(): invalid chunk size
E0802 11:53:12.371311311 1358394 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
INFO flwr 2023-08-02 11:53:31,112 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:53:31,112 | fed_df.py:523 | Average fusion training loss : 0.07271712338924408, val accuracy : 0.72316, best val accuracy : 0.7326
Average local training loss : 3.7720700830221174
Average local training accuracy : 0.9020666666666667
INFO flwr 2023-08-02 11:53:32,340 | server.py:116 | fit progress: (19, 1.2879918914794921, {'server_test_acc': 0.734}, 1759.693358282093)
INFO flwr 2023-08-02 11:53:32,341 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-02 11:53:41,648 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-02 11:54:29,466 | server.py:229 | fit_round 20 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1375867)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:54:29,683 | fed_df.py:351 | Warm start at round 20
[2m[36m(launch_and_fit pid=1375854)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 11:54:29,795 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1375854)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1375852)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1375856)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1375859)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1375858)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1375865)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1375866)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1375867)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1375865)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1375856)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1375852)[0m malloc_consolidate(): invalid chunk size
E0802 11:54:30.957020494 1423502 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=1375859)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1375866)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1375858)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:55:01,163 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:55:01,164 | fed_df.py:523 | Average fusion training loss : 0.08911857438087463, val accuracy : 0.72752, best val accuracy : 0.7324
Average local training loss : 3.7886556643992666
Average local training accuracy : 0.899988888888889
INFO flwr 2023-08-02 11:55:02,366 | server.py:116 | fit progress: (20, 1.2774008483886719, {'server_test_acc': 0.7329}, 1849.719057087088)
INFO flwr 2023-08-02 11:55:02,366 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-02 11:55:11,604 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-02 11:55:58,933 | server.py:229 | fit_round 21 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1448731)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 11:55:59,149 | fed_df.py:351 | Warm start at round 21
INFO flwr 2023-08-02 11:55:59,260 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1448731)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1448733)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1448734)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1448736)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1448737)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1448738)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1448739)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1448740)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1448740)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1448734)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1448738)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1448739)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1448736)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1448733)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1448737)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 11:56:30,021 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:56:30,022 | fed_df.py:523 | Average fusion training loss : 0.0846085774153471, val accuracy : 0.73544, best val accuracy : 0.7442
Average local training loss : 3.8344678137451407
Average local training accuracy : 0.8951083333333333
INFO flwr 2023-08-02 11:56:31,229 | server.py:116 | fit progress: (21, 1.2680948944091797, {'server_test_acc': 0.7433}, 1938.5818893141113)
INFO flwr 2023-08-02 11:56:31,229 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-02 11:56:40,515 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1521705)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:57:28,154 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-02 11:57:28,369 | fed_df.py:351 | Warm start at round 22
INFO flwr 2023-08-02 11:57:28,483 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1521703)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1521705)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1521709)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1521704)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1521707)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1521708)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1521711)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1521710)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1521709)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1521707)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1521703)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1521710)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1521711)[0m double free or corruption (fasttop)
E0802 11:57:29.587240856 1569550 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1521704)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1521708)[0m double free or corruption (fasttop)
E0802 11:57:41.442872982 1569620 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-02 11:57:59,928 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:57:59,928 | fed_df.py:523 | Average fusion training loss : 0.10225148916244507, val accuracy : 0.7240800000000001, best val accuracy : 0.7354
Average local training loss : 3.6431203328073027
Average local training accuracy : 0.9120166666666667
INFO flwr 2023-08-02 11:58:01,141 | server.py:116 | fit progress: (22, 1.2018399505615234, {'server_test_acc': 0.7311}, 2028.4940476301126)
INFO flwr 2023-08-02 11:58:01,141 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-02 11:58:10,380 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1607509)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-02 11:58:57,904 | server.py:229 | fit_round 23 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1607503)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:58:58,126 | fed_df.py:351 | Warm start at round 23
INFO flwr 2023-08-02 11:58:58,241 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1607503)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1607506)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1607509)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1607511)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1607512)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1607510)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1607504)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1607508)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1607506)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1607504)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1607511)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1607512)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1607510)[0m double free or corruption (fasttop)
E0802 11:58:59.498266113 1669086 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1607508)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:59:34,766 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:59:34,767 | fed_df.py:523 | Average fusion training loss : 0.09872063010931015, val accuracy : 0.73248, best val accuracy : 0.7462
Average local training loss : 3.7411142490804195
Average local training accuracy : 0.9035888888888889
INFO flwr 2023-08-02 11:59:35,980 | server.py:116 | fit progress: (23, 1.2421655639648437, {'server_test_acc': 0.7449}, 2123.3328170010354)
INFO flwr 2023-08-02 11:59:35,980 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-02 11:59:45,510 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1696068)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-02 12:00:33,343 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-02 12:00:33,560 | fed_df.py:351 | Warm start at round 24
INFO flwr 2023-08-02 12:00:33,674 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1696070)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1696072)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1696068)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1696074)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1696075)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1696073)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1696076)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1696077)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1696074)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1696073)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1696077)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1696072)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1696070)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1696076)[0m double free or corruption (fasttop)
E0802 12:00:35.007446843 1669412 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1696075)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 12:01:05,861 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 12:01:05,862 | fed_df.py:523 | Average fusion training loss : 0.08294557209312915, val accuracy : 0.7568400000000001, best val accuracy : 0.7612
Average local training loss : 3.726101180538535
Average local training accuracy : 0.9060916666666665
INFO flwr 2023-08-02 12:01:07,076 | server.py:116 | fit progress: (24, 1.176593194580078, {'server_test_acc': 0.7527}, 2214.428820433095)
INFO flwr 2023-08-02 12:01:07,076 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-02 12:01:16,556 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-02 12:02:03,908 | server.py:229 | fit_round 25 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1769184)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1769168)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 12:02:04,127 | fed_df.py:351 | Warm start at round 25
INFO flwr 2023-08-02 12:02:04,240 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1769168)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1769178)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1769166)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1769176)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1769184)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1769177)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1769183)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1769170)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1769170)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1769183)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1769176)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1769178)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1769166)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1769177)[0m double free or corruption (fasttop)
E0802 12:02:05.667339001 1744600 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0802 12:02:05.667444929 1744600 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0802 12:02:05.667461915 1744600 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-02 12:02:36,174 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 12:02:36,174 | fed_df.py:523 | Average fusion training loss : 0.08667370097339153, val accuracy : 0.74968, best val accuracy : 0.7556
Average local training loss : 3.607420190423727
Average local training accuracy : 0.9147833333333334
INFO flwr 2023-08-02 12:02:37,405 | server.py:116 | fit progress: (25, 1.092860220336914, {'server_test_acc': 0.7579}, 2304.7577305131126)
INFO flwr 2023-08-02 12:02:37,405 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-02 12:02:46,813 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1842137)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 12:03:34,569 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-02 12:03:34,787 | fed_df.py:351 | Warm start at round 26
INFO flwr 2023-08-02 12:03:34,915 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1842137)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1842136)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1842138)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1842139)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1842141)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1842143)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1842140)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1842142)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1842141)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1842143)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1842140)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1842139)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1842142)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1842138)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1842136)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 12:04:07,208 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 12:04:07,209 | fed_df.py:523 | Average fusion training loss : 0.08270563779771328, val accuracy : 0.74476, best val accuracy : 0.7524
Average local training loss : 3.614914567023516
Average local training accuracy : 0.9143194444444444
INFO flwr 2023-08-02 12:04:08,563 | server.py:116 | fit progress: (26, 1.16852880859375, {'server_test_acc': 0.7545}, 2395.916156512918)
INFO flwr 2023-08-02 12:04:08,563 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-02 12:04:17,864 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1915015)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1915019)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-02 12:05:05,820 | server.py:229 | fit_round 27 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1915020)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 12:05:06,035 | fed_df.py:351 | Warm start at round 27
INFO flwr 2023-08-02 12:05:06,146 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1915017)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1915013)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1915015)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1915019)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1915018)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1915020)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1915022)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1915021)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1915021)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1915018)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1915013)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1915017)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1915022)[0m malloc_consolidate(): invalid chunk size
E0802 12:05:08.639101103 1963420 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0802 12:05:08.639204094 1963420 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0802 12:05:08.639217307 1963420 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-02 12:05:37,099 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 12:05:37,099 | fed_df.py:523 | Average fusion training loss : 0.10282821464538575, val accuracy : 0.75572, best val accuracy : 0.7604
Average local training loss : 3.6001589797437195
Average local training accuracy : 0.9155055555555556
INFO flwr 2023-08-02 12:05:38,445 | server.py:116 | fit progress: (27, 1.1254174987792969, {'server_test_acc': 0.7594}, 2485.7983043310232)
INFO flwr 2023-08-02 12:05:38,446 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-02 12:05:47,719 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1987970)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 12:06:35,292 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-02 12:06:35,508 | fed_df.py:351 | Warm start at round 28
INFO flwr 2023-08-02 12:06:35,621 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1987970)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1987982)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1987977)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1987981)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1987979)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1987980)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1987976)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1987978)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1987978)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1987982)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1987979)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1987977)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1987980)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1987981)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1987976)[0m malloc_consolidate(): invalid chunk size
E0802 12:06:37.672750082 1964148 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-02 12:07:07,191 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 12:07:07,192 | fed_df.py:523 | Average fusion training loss : 0.10184828868508339, val accuracy : 0.7402, best val accuracy : 0.7468
Average local training loss : 3.5499493602663277
Average local training accuracy : 0.9203361111111112
INFO flwr 2023-08-02 12:07:08,569 | server.py:116 | fit progress: (28, 1.1937609191894532, {'server_test_acc': 0.7492}, 2575.921583275078)
INFO flwr 2023-08-02 12:07:08,569 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-02 12:07:17,880 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2060866)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 12:08:05,318 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-02 12:08:05,535 | fed_df.py:351 | Warm start at round 29
INFO flwr 2023-08-02 12:08:05,646 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2060866)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2060871)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2060873)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2060875)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2060869)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2060872)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2060870)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2060874)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2060873)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2060875)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2060872)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2060874)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2060870)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2060869)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2060871)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 12:08:37,190 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 12:08:37,191 | fed_df.py:523 | Average fusion training loss : 0.08698171550035477, val accuracy : 0.7458400000000001, best val accuracy : 0.7546
Average local training loss : 3.570677422732115
Average local training accuracy : 0.9180222222222223
INFO flwr 2023-08-02 12:08:38,577 | server.py:116 | fit progress: (29, 1.161540692138672, {'server_test_acc': 0.7575}, 2665.9302113850135)
INFO flwr 2023-08-02 12:08:38,578 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-02 12:08:47,864 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-02 12:09:35,534 | server.py:229 | fit_round 30 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2133717)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2133729)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 12:09:35,753 | fed_df.py:351 | Warm start at round 30
INFO flwr 2023-08-02 12:09:35,863 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2133717)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2133719)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2133728)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2133729)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2133727)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2133730)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2133726)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2133731)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2133719)[0m malloc_consolidate(): invalid chunk size
E0802 12:09:36.495799436 2036766 chttp2_transport.cc:1079]             ipv4:145.136.62.63:57443: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2133730)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2133727)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2133728)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2133726)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2133731)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 12:10:07,461 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 12:10:07,462 | fed_df.py:523 | Average fusion training loss : 0.0918336198925972, val accuracy : 0.7372400000000001, best val accuracy : 0.7466
Average local training loss : 3.4803935606032614
Average local training accuracy : 0.9251055555555555
INFO flwr 2023-08-02 12:10:08,765 | server.py:116 | fit progress: (30, 1.143637252807617, {'server_test_acc': 0.7467}, 2756.1182886019815)
INFO flwr 2023-08-02 12:10:08,766 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-02 12:10:08,766 | server.py:144 | FL finished in 2756.1186252241023
INFO flwr 2023-08-02 12:10:08,766 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-02 12:10:08,767 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-02 12:10:08,767 | app.py:204 | app_fit: losses_centralized [(0, 2.3234217651367186), (1, 3.7691418701171875), (2, 3.7104874877929688), (3, 1.9877834533691405), (4, 1.4462037994384767), (5, 1.2386199401855469), (6, 1.2686992126464844), (7, 1.2843581481933595), (8, 1.1879063385009765), (9, 1.3039254455566407), (10, 1.2950278350830078), (11, 1.2979467559814453), (12, 1.2877573364257813), (13, 1.2806775909423829), (14, 1.2081013366699218), (15, 1.1851177520751952), (16, 1.278918194580078), (17, 1.38278583984375), (18, 1.3021061767578126), (19, 1.2879918914794921), (20, 1.2774008483886719), (21, 1.2680948944091797), (22, 1.2018399505615234), (23, 1.2421655639648437), (24, 1.176593194580078), (25, 1.092860220336914), (26, 1.16852880859375), (27, 1.1254174987792969), (28, 1.1937609191894532), (29, 1.161540692138672), (30, 1.143637252807617)]
INFO flwr 2023-08-02 12:10:08,767 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.108), (1, 0.3041), (2, 0.3992), (3, 0.522), (4, 0.5876), (5, 0.6376), (6, 0.6632), (7, 0.6755), (8, 0.6907), (9, 0.6927), (10, 0.704), (11, 0.7099), (12, 0.7212), (13, 0.722), (14, 0.7355), (15, 0.735), (16, 0.7228), (17, 0.7176), (18, 0.7384), (19, 0.734), (20, 0.7329), (21, 0.7433), (22, 0.7311), (23, 0.7449), (24, 0.7527), (25, 0.7579), (26, 0.7545), (27, 0.7594), (28, 0.7492), (29, 0.7575), (30, 0.7467)]}
double free or corruption (fasttop)
srun: error: gcn63: task 0: Aborted
srun: Terminating StepId=3203518.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3203518
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 01:53:37
CPU Efficiency: 11.85% of 15:58:30 core-walltime
Job Wall-clock time: 00:53:15
Memory Utilized: 56.54 GB
Memory Efficiency: 47.12% of 120.00 GB
