-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:50000
STRATEGY:feddf_hetero
MODEL_NAME:wresnet-16-4
MODEL_LIST:{'resnet8':7,'wresnet-16-4':7,'resnet20':6}
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:40
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:32
SERVER_LR:0.005
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SERVER_STEPS:500
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
SERVER_STEPS_ADAPTIVE:False
SERVER_STEPS_ADAPTIVE_MIN:100
SERVER_STEPS_ADAPTIVE_INTERVAL:5
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko_small.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:2.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:True
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=50000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko_small.jpg', targetpath='/scratch-local/sunnys.3926529/1695680922_569621389', seed=42, img_per_thread=2777)
will save 50000 patches in /scratch-local/sunnys.3926529/1695680922_569621389/single_img_crops/crops
50000 took 1.06min with 18 threads
---------
Simulating feddf_hetero training
INFO simulate 2023-09-26 00:30:04,977 | simulate.py:51 | Python script started : simulate.py
DEBUG simulate 2023-09-26 00:30:04,978 | simulate.py:56 | Reading args from argument parser
INFO flwr 2023-09-26 00:30:54,821 | fed_df_hetero.py:193 | Models in the server : ['resnet8', 'wresnet-16-4', 'resnet20']
INFO flwr 2023-09-26 00:30:54,900 | fed_df_hetero.py:198 | Server Models initialised
INFO flwr 2023-09-26 00:30:54,901 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-09-26 00:30:57,809	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-09-26 00:30:59,110 | app.py:179 | Flower VCE: Ray initialized with resources: {'CPU': 18.0, 'accelerator_type:A100': 1.0, 'object_store_memory': 61847529062.0, 'memory': 103079215104.0, 'node:145.136.62.34': 1.0, 'GPU': 1.0}
INFO flwr 2023-09-26 00:30:59,110 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-26 00:30:59,110 | server.py:270 | Requesting initial parameters from one random client
INFO flwr 2023-09-26 00:31:05,673 | server.py:274 | Received initial parameters from one random client
INFO flwr 2023-09-26 00:31:05,673 | server.py:88 | Evaluating initial parameters
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3926529/1695680922_569621389/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3926529/1695680922_569621389/cifar-10-python.tar.gz to /scratch-local/sunnys.3926529/1695680922_569621389
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [440 381 415  39  10 257 227 532  17 182]
[2m[36m(launch_and_get_parameters pid=1829942)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 00:31:13,205 | server.py:91 | initial parameters (loss, other metrics): 3.7793668823242186, {'server_test_acc': 0.1}
INFO flwr 2023-09-26 00:31:13,206 | server.py:101 | FL starting
[2m[36m(launch_and_get_properties pid=1831496)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1831927)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1832334)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1832680)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1833004)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1833348)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1833717)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 00:31:57,672 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=1834038)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 00:32:09,737 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1835269)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1835251)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1835263)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1835248)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1835250)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1835241)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 00:33:27,771 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-09-26 00:33:27,881 | fed_df_hetero.py:400 | Warm start at round 1
[2m[36m(launch_and_fit pid=1835247)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1835249)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1930862)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1931342)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1931815)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1932295)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1933081)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1933548)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1934027)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 00:34:12,247 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 00:34:12,310 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 00:34:12,374 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 00:34:12,374 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=1835241)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1835251)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1835247)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1835250)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1835248)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1835249)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1835269)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1835263)[0m Fitting Client 17
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=1934452)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 00:34:38,049 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.25219506487250326, 'fusion_acc': 0.27007272727272724}, {'fusion_loss': 0.2411048138141632, 'fusion_acc': 0.24690909090909097}, {'fusion_loss': 0.2632682832181454, 'fusion_acc': 0.24894545454545455}]
INFO flwr 2023-09-26 00:34:38,050 | common.py:35 | Avg. local train loss : 6.732096059806646, train acc : 0.5975902777777777
INFO flwr 2023-09-26 00:34:45,109 | server.py:116 | fit progress: (1, 3.480742150878906, {'server_test_acc': 0.3312}, 211.9034420819953)
INFO flwr 2023-09-26 00:34:45,109 | server.py:163 | evaluate_round 1: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=1943570)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1943974)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1944343)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1944809)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1945288)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1945767)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1946589)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 00:35:29,328 | fed_df_hetero.py:270 | Best Server Model Name : resnet20
[2m[36m(launch_and_get_properties pid=1947107)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 00:35:46,471 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1948965)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1948970)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1948957)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1948971)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1948967)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1948969)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 00:37:01,106 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-09-26 00:37:01,216 | fed_df_hetero.py:400 | Warm start at round 2
[2m[36m(launch_and_fit pid=1948947)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1948968)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2043350)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2043854)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2044356)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2045155)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2045705)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2046220)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2046709)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 00:37:45,351 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 00:37:45,394 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 00:37:45,438 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 00:37:45,438 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=1948947)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1948968)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1948965)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1948957)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1948969)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1948970)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1948971)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1948967)[0m Fitting Client 17
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=2047229)[0m malloc_consolidate(): invalid chunk size
E0926 00:37:49.190944143 1829937 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-09-26 00:38:10,357 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.21183110068738462, 'fusion_acc': 0.44038181818181815}, {'fusion_loss': 0.21383888989686967, 'fusion_acc': 0.43327272727272725}, {'fusion_loss': 0.20711138240993024, 'fusion_acc': 0.4419272727272727}]
INFO flwr 2023-09-26 00:38:10,357 | common.py:35 | Avg. local train loss : 5.623297191038728, train acc : 0.7086652777777778
INFO flwr 2023-09-26 00:38:17,478 | server.py:116 | fit progress: (2, 2.5099783203125, {'server_test_acc': 0.495}, 424.2723774659971)
INFO flwr 2023-09-26 00:38:17,478 | server.py:163 | evaluate_round 2: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=2069525)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2079267)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2082539)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2083094)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2085627)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2090126)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2092444)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 00:39:02,053 | fed_df_hetero.py:270 | Best Server Model Name : resnet20
[2m[36m(launch_and_get_properties pid=2097432)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 00:39:19,341 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2102150)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2102145)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2102140)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2102147)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2102142)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 00:40:39,273 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-09-26 00:40:39,383 | fed_df_hetero.py:400 | Warm start at round 3
[2m[36m(launch_and_fit pid=2102146)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2102149)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2102151)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2197715)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2198233)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2198717)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2199163)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2199566)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2199947)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2200295)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 00:41:23,751 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 00:41:23,838 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 00:41:23,880 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 00:41:23,880 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=2102140)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2102142)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2102149)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2102147)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2102146)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2102151)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2102145)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2102150)[0m Fitting Client 0
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=2201279)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 00:41:48,770 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.3849176658987999, 'fusion_acc': 0.4375454545454545}, {'fusion_loss': 0.3494377728998661, 'fusion_acc': 0.5058181818181818}, {'fusion_loss': 0.435848212569952, 'fusion_acc': 0.4064363636363636}]
INFO flwr 2023-09-26 00:41:48,771 | common.py:35 | Avg. local train loss : 4.232227425277234, train acc : 0.8460777777777777
INFO flwr 2023-09-26 00:41:55,836 | server.py:116 | fit progress: (3, 3.5162487854003905, {'server_test_acc': 0.4803}, 642.6299343669962)
INFO flwr 2023-09-26 00:41:55,836 | server.py:163 | evaluate_round 3: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=2210737)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2211253)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2211783)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2212330)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2212890)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2213690)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2214283)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 00:42:39,856 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=2214813)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 00:42:51,785 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2216732)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2216734)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2216733)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2216724)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2216728)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 00:44:14,372 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-09-26 00:44:14,482 | fed_df_hetero.py:400 | Warm start at round 4
[2m[36m(launch_and_fit pid=2216737)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2216730)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2216736)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2312488)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2313226)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2313605)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2313968)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2314334)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2314756)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2315359)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 00:44:58,747 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 00:44:58,850 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 00:44:58,874 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 00:44:58,874 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=2216724)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2216728)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2216736)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2216730)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2216734)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2216732)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2216733)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2216737)[0m Fitting Client 11
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=2315898)[0m double free or corruption (fasttop)
E0926 00:45:02.943668035 2317785 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
INFO flwr 2023-09-26 00:45:23,408 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.2598983642458916, 'fusion_acc': 0.4203818181818182}, {'fusion_loss': 0.2242701553106308, 'fusion_acc': 0.49483636363636374}, {'fusion_loss': 0.26750075313448907, 'fusion_acc': 0.4278}]
INFO flwr 2023-09-26 00:45:23,408 | common.py:35 | Avg. local train loss : 4.0421637976542115, train acc : 0.8683722222222222
INFO flwr 2023-09-26 00:45:30,570 | server.py:116 | fit progress: (4, 3.7858687744140624, {'server_test_acc': 0.5079}, 857.3646960179976)
INFO flwr 2023-09-26 00:45:30,571 | server.py:163 | evaluate_round 4: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=2326084)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2326626)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2327151)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2327922)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2328350)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2328779)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2329139)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 00:46:15,160 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=2329493)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 00:46:30,996 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2331035)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2331043)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2331045)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2331042)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2331046)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2331040)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 00:47:46,827 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-09-26 00:47:46,938 | fed_df_hetero.py:400 | Warm start at round 5
[2m[36m(launch_and_fit pid=2331037)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2331041)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2426716)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2427250)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2427774)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2428333)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2428840)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2429354)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2429922)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 00:48:31,404 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 00:48:31,445 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 00:48:31,507 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 00:48:31,507 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=2331035)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2331037)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2331042)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2331041)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2331043)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2331045)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2331046)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2331040)[0m Fitting Client 15
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=2430452)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 00:48:56,401 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.20102752113342284, 'fusion_acc': 0.4908181818181819}, {'fusion_loss': 0.2164669577330351, 'fusion_acc': 0.48352727272727286}, {'fusion_loss': 0.17555134652554988, 'fusion_acc': 0.5659272727272728}]
INFO flwr 2023-09-26 00:48:56,401 | common.py:35 | Avg. local train loss : 3.7301683101803063, train acc : 0.9072791666666666
INFO flwr 2023-09-26 00:49:03,554 | server.py:116 | fit progress: (5, 3.470958093261719, {'server_test_acc': 0.5963}, 1070.3479313079952)
INFO flwr 2023-09-26 00:49:03,554 | server.py:163 | evaluate_round 5: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=2440514)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2440944)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2441338)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2442028)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2442388)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_get_properties pid=2442760)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2443111)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 00:49:47,671 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=2443473)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 00:50:03,400 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2445189)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2445187)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2445170)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2445171)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2445190)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2445169)[0m corrupted size vs. prev_size in fastbins
DEBUG flwr 2023-09-26 00:51:24,526 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-09-26 00:51:24,636 | fed_df_hetero.py:400 | Warm start at round 6
[2m[36m(launch_and_fit pid=2445191)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2445188)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2540984)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2541341)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2541689)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2542054)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2542409)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2543203)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2543737)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 00:52:08,803 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 00:52:08,883 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 00:52:08,944 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 00:52:08,944 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=2445171)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2445169)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2445170)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2445190)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2445189)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2445188)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2445187)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2445191)[0m Fitting Client 9
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=2544271)[0m double free or corruption (fasttop)
E0926 00:52:11.242186986 2506004 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-09-26 00:52:33,705 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.3106354448199272, 'fusion_acc': 0.4168181818181818}, {'fusion_loss': 0.282993293017149, 'fusion_acc': 0.5631636363636363}, {'fusion_loss': 0.25195258256793024, 'fusion_acc': 0.5561636363636363}]
INFO flwr 2023-09-26 00:52:33,705 | common.py:35 | Avg. local train loss : 3.367241879552603, train acc : 0.9318027777777778
INFO flwr 2023-09-26 00:52:40,894 | server.py:116 | fit progress: (6, 4.435352136230469, {'server_test_acc': 0.5882}, 1287.6884238779967)
INFO flwr 2023-09-26 00:52:40,894 | server.py:163 | evaluate_round 6: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=2554031)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2554524)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2555061)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2555552)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2556079)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2556577)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2557078)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 00:53:24,845 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=2558188)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 00:53:40,707 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2560024)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2560046)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2560030)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2560029)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2560028)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 00:55:00,070 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-09-26 00:55:00,180 | fed_df_hetero.py:400 | Warm start at round 7
[2m[36m(launch_and_fit pid=2560025)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2560022)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2560047)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2678641)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2679623)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2680099)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2683659)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_get_properties pid=2687119)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2691460)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2694344)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 00:55:44,493 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 00:55:44,557 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 00:55:44,599 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 00:55:44,599 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=2560025)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2560024)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2560022)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2560030)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2560029)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2560028)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2560047)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2560046)[0m Fitting Client 0
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=2698221)[0m malloc_consolidate(): invalid chunk size
E0926 00:56:02.460775609 2704134 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-09-26 00:56:09,723 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.1696929448992014, 'fusion_acc': 0.5056}, {'fusion_loss': 0.16134296640008688, 'fusion_acc': 0.6048181818181818}, {'fusion_loss': 0.1314413335695863, 'fusion_acc': 0.5782181818181817}]
INFO flwr 2023-09-26 00:56:09,723 | common.py:35 | Avg. local train loss : 3.5487194005399934, train acc : 0.9191944444444445
INFO flwr 2023-09-26 00:56:16,896 | server.py:116 | fit progress: (7, 3.265357989501953, {'server_test_acc': 0.6292}, 1503.6904944389971)
INFO flwr 2023-09-26 00:56:16,896 | server.py:163 | evaluate_round 7: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=2708117)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2708681)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_get_properties pid=2709097)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2709479)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2709825)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2710154)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2710516)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 00:57:00,547 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=2710862)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 00:57:12,510 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2712029)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2712025)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2712028)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2712021)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2712026)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2712030)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 00:58:27,242 | server.py:229 | fit_round 8 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2712027)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 00:58:27,352 | fed_df_hetero.py:400 | Warm start at round 8
[2m[36m(launch_and_fit pid=2712033)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2808000)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2808525)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2809016)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2809508)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2810015)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2810510)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2811008)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 00:59:11,675 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 00:59:11,717 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 00:59:11,740 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 00:59:11,740 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=2712027)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2712033)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2712021)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2712029)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2712025)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2712030)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2712026)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2712028)[0m Fitting Client 2
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=2811510)[0m double free or corruption (fasttop)
E0926 00:59:13.818483651 2704957 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-09-26 00:59:36,720 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.20426750603318214, 'fusion_acc': 0.5589636363636363}, {'fusion_loss': 0.18839261589199305, 'fusion_acc': 0.6369090909090909}, {'fusion_loss': 0.1633261531293392, 'fusion_acc': 0.6315636363636363}]
INFO flwr 2023-09-26 00:59:36,720 | common.py:35 | Avg. local train loss : 3.6998844159767033, train acc : 0.9196902777777778
INFO flwr 2023-09-26 00:59:43,829 | server.py:116 | fit progress: (8, 3.103964959716797, {'server_test_acc': 0.6554}, 1710.623296963)
INFO flwr 2023-09-26 00:59:43,829 | server.py:163 | evaluate_round 8: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=2821486)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2821977)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2822384)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2822785)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2823185)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2823514)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2823860)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:00:27,550 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=2824237)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:00:39,389 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2825297)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2825296)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2825287)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2825290)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2825314)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 01:01:59,768 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-09-26 01:01:59,878 | fed_df_hetero.py:400 | Warm start at round 9
[2m[36m(launch_and_fit pid=2825295)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2825298)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2825315)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2921282)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2921720)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2922057)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2922398)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2923063)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2923684)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2924031)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:02:44,605 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 01:02:44,666 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 01:02:44,726 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 01:02:44,726 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=2825287)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2825290)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2825298)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2825295)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2825297)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2825296)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2825315)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2825314)[0m Fitting Client 17
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=2924360)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:03:09,593 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.3918078657090664, 'fusion_acc': 0.47870909090909086}, {'fusion_loss': 0.3302874046564102, 'fusion_acc': 0.6234909090909091}, {'fusion_loss': 0.29034926387667653, 'fusion_acc': 0.6328}]
INFO flwr 2023-09-26 01:03:09,593 | common.py:35 | Avg. local train loss : 3.23330055475235, train acc : 0.9482375
INFO flwr 2023-09-26 01:03:16,733 | server.py:116 | fit progress: (9, 4.302023095703125, {'server_test_acc': 0.6535}, 1923.5272760239968)
INFO flwr 2023-09-26 01:03:16,733 | server.py:163 | evaluate_round 9: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=2933922)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2934426)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2934899)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2935375)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2935882)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2936369)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2937149)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:04:01,047 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=2937623)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 01:04:16,567 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2939339)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2939336)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2939340)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2939342)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2939337)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:05:37,554 | server.py:229 | fit_round 10 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2939333)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:05:37,665 | fed_df_hetero.py:400 | Warm start at round 10
[2m[36m(launch_and_fit pid=2939334)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2939341)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3035165)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3035530)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3035883)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3036210)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3036575)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3036909)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3037236)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 01:06:21,846 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 01:06:21,946 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 01:06:21,946 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=2939333)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2939337)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2939341)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2939340)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2939342)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2939339)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2939336)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2939334)[0m Fitting Client 8
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=3037585)[0m malloc_consolidate(): invalid chunk size
E0926 01:06:27.961522257 3036341 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-09-26 01:06:46,941 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.11476673056930303, 'fusion_acc': 0.4788363636363637}, {'fusion_loss': 0.11069727677106857, 'fusion_acc': 0.6099454545454545}, {'fusion_loss': 0.10763247527182102, 'fusion_acc': 0.5215272727272727}]
INFO flwr 2023-09-26 01:06:46,942 | common.py:35 | Avg. local train loss : 3.136234511807561, train acc : 0.9614125
INFO flwr 2023-09-26 01:06:54,144 | server.py:116 | fit progress: (10, 4.466257470703125, {'server_test_acc': 0.6583}, 2140.9381503569966)
INFO flwr 2023-09-26 01:06:54,144 | server.py:163 | evaluate_round 10: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=3047737)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3048206)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3048665)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3049136)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3049613)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3050111)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3050587)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:07:38,177 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=3051047)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:07:53,742 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3052289)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3052301)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3052306)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3052302)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3052285)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:09:09,321 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-09-26 01:09:09,432 | fed_df_hetero.py:400 | Warm start at round 11
[2m[36m(launch_and_fit pid=3052303)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3052304)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3052283)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3146807)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3147267)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3148099)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_get_properties pid=3148590)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3149056)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3149514)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3149997)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:09:53,500 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 01:09:53,563 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 01:09:53,605 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 01:09:53,605 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=3052283)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3052285)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3052301)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3052306)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3052303)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3052289)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3052304)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3052302)[0m Fitting Client 18
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=3150750)[0m malloc_consolidate(): invalid chunk size
E0926 01:10:04.679509828 3160433 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-09-26 01:10:18,858 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.2646506094485521, 'fusion_acc': 0.5457090909090909}, {'fusion_loss': 0.24467642027139663, 'fusion_acc': 0.6142181818181819}, {'fusion_loss': 0.20333003835380078, 'fusion_acc': 0.5880363636363637}]
INFO flwr 2023-09-26 01:10:18,858 | common.py:35 | Avg. local train loss : 3.189483423531055, train acc : 0.9544513888888889
INFO flwr 2023-09-26 01:10:26,157 | server.py:116 | fit progress: (11, 3.8037269165039063, {'server_test_acc': 0.6259}, 2352.951718021999)
INFO flwr 2023-09-26 01:10:26,158 | server.py:163 | evaluate_round 11: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=3182913)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3185015)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3185527)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3187472)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3192497)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3194135)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3197504)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:11:10,565 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=3203089)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:11:26,208 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3205339)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3205337)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3205338)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3205333)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3205343)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 01:12:43,203 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-09-26 01:12:43,314 | fed_df_hetero.py:400 | Warm start at round 12
[2m[36m(launch_and_fit pid=3205340)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3205342)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3205344)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3299373)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3300153)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3300607)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_get_properties pid=3301062)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3301517)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3301969)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3302424)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 01:13:27,632 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 01:13:27,697 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 01:13:27,743 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 01:13:27,743 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=3205333)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3205337)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3205340)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3205339)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3205338)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3205344)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3205342)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3205343)[0m Fitting Client 14
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=3303217)[0m malloc_consolidate(): invalid chunk size
E0926 01:13:31.312625487 3304961 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-09-26 01:13:52,931 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.26639036723971365, 'fusion_acc': 0.5280727272727272}, {'fusion_loss': 0.24949437484145165, 'fusion_acc': 0.6562545454545454}, {'fusion_loss': 0.21115442959964276, 'fusion_acc': 0.6828000000000001}]
INFO flwr 2023-09-26 01:13:52,931 | common.py:35 | Avg. local train loss : 3.17013156786561, train acc : 0.9573236111111111
INFO flwr 2023-09-26 01:14:00,222 | server.py:116 | fit progress: (12, 2.73856884765625, {'server_test_acc': 0.697}, 2567.0158200679944)
INFO flwr 2023-09-26 01:14:00,222 | server.py:163 | evaluate_round 12: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=3311943)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3312262)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3312590)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3312976)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3313748)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3314464)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_get_properties pid=3314915)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:14:44,305 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=3315372)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 01:15:00,307 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3317006)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3317001)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3317012)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3317003)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3317008)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3317011)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 01:16:17,704 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-09-26 01:16:17,815 | fed_df_hetero.py:400 | Warm start at round 13
[2m[36m(launch_and_fit pid=3317000)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3317013)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3412085)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3412563)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3413016)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3413472)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3413925)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3414351)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_get_properties pid=3414834)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:17:01,427 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 01:17:01,479 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 01:17:01,541 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 01:17:01,541 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=3317001)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3317003)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3317000)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3317006)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3317011)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3317008)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3317013)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3317012)[0m Fitting Client 5
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=3415285)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:17:26,543 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.32032257616519927, 'fusion_acc': 0.5107090909090909}, {'fusion_loss': 0.3136625080704689, 'fusion_acc': 0.6038727272727274}, {'fusion_loss': 0.20985745266079903, 'fusion_acc': 0.6499090909090909}]
INFO flwr 2023-09-26 01:17:26,543 | common.py:35 | Avg. local train loss : 3.1201354647986586, train acc : 0.9599083333333335
INFO flwr 2023-09-26 01:17:33,694 | server.py:116 | fit progress: (13, 3.905578369140625, {'server_test_acc': 0.6597}, 2780.488081423995)
INFO flwr 2023-09-26 01:17:33,694 | server.py:163 | evaluate_round 13: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=3425173)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3425538)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3425849)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3426193)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3426521)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3426830)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3427161)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:18:17,854 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=3427482)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:18:30,135 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3429148)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3429154)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3429152)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3429155)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3429156)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3429117)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:19:49,568 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-09-26 01:19:49,680 | fed_df_hetero.py:400 | Warm start at round 14
[2m[36m(launch_and_fit pid=3429135)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3429157)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3524120)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3524416)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3524744)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3525097)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_get_properties pid=3525371)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3525711)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3526352)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:20:33,603 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 01:20:33,669 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 01:20:33,732 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 01:20:33,732 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=3429117)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3429152)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3429135)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3429154)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3429155)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3429148)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3429157)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3429156)[0m Fitting Client 16
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=3526764)[0m malloc_consolidate(): invalid chunk size
E0926 01:20:38.799261193 3529272 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-09-26 01:20:59,060 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.5788061197400093, 'fusion_acc': 0.48385454545454554}, {'fusion_loss': 0.4906624602675438, 'fusion_acc': 0.6519090909090909}, {'fusion_loss': 0.3817851512134075, 'fusion_acc': 0.6187454545454545}]
INFO flwr 2023-09-26 01:20:59,060 | common.py:35 | Avg. local train loss : 3.0882459284737704, train acc : 0.9582513888888887
INFO flwr 2023-09-26 01:21:06,286 | server.py:116 | fit progress: (14, 6.9386432861328124, {'server_test_acc': 0.6405}, 2993.0806682849943)
INFO flwr 2023-09-26 01:21:06,287 | server.py:163 | evaluate_round 14: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=3536144)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3536554)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3537029)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3537803)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3538239)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3538692)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3539131)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:21:50,719 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=3539585)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:22:06,596 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3541449)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3541447)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3541456)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3541450)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3541455)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3541473)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 01:23:22,097 | server.py:229 | fit_round 15 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3541472)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 01:23:22,209 | fed_df_hetero.py:400 | Warm start at round 15
[2m[36m(launch_and_fit pid=3541471)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3636602)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3637039)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3637503)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3637953)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3638347)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3638742)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3639080)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:24:06,214 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 01:24:06,240 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 01:24:06,341 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 01:24:06,341 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=3541449)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3541447)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3541450)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3541473)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3541471)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3541456)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3541472)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3541455)[0m Fitting Client 18
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=3639405)[0m double free or corruption (fasttop)
E0926 01:24:17.104626321 3642315 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
INFO flwr 2023-09-26 01:24:31,673 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.6350558432340622, 'fusion_acc': 0.4638727272727273}, {'fusion_loss': 0.6336121307611465, 'fusion_acc': 0.506381818181818}, {'fusion_loss': 0.41777593860030177, 'fusion_acc': 0.6010181818181818}]
INFO flwr 2023-09-26 01:24:31,673 | common.py:35 | Avg. local train loss : 2.9984573520720006, train acc : 0.9660416666666667
INFO flwr 2023-09-26 01:24:38,923 | server.py:116 | fit progress: (15, 7.57085703125, {'server_test_acc': 0.6201}, 3205.717172906996)
INFO flwr 2023-09-26 01:24:38,923 | server.py:163 | evaluate_round 15: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=3648205)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3648636)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3649442)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3649895)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3650315)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3650753)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3651206)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 01:25:22,631 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=3651629)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:25:34,713 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3653375)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3653363)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3653392)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3653391)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3653397)[0m corrupted size vs. prev_size in fastbins
DEBUG flwr 2023-09-26 01:26:55,010 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-09-26 01:26:55,121 | fed_df_hetero.py:400 | Warm start at round 16
[2m[36m(launch_and_fit pid=3653360)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3653398)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3653396)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3772215)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3778210)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3779503)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3780956)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3785517)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3789597)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3790057)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:27:39,311 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 01:27:39,372 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 01:27:39,452 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 01:27:39,452 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=3653360)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3653363)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3653391)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3653375)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3653392)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3653396)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3653398)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3653397)[0m Fitting Client 18
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=3790485)[0m double free or corruption (fasttop)
E0926 01:27:42.621694072 3643306 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
INFO flwr 2023-09-26 01:28:04,696 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.63883508259058, 'fusion_acc': 0.4856}, {'fusion_loss': 0.5744336186051369, 'fusion_acc': 0.6596000000000001}, {'fusion_loss': 0.4338844655752182, 'fusion_acc': 0.6119636363636365}]
INFO flwr 2023-09-26 01:28:04,696 | common.py:35 | Avg. local train loss : 2.892529715504497, train acc : 0.9700874999999999
INFO flwr 2023-09-26 01:28:11,964 | server.py:116 | fit progress: (16, 5.090053894042969, {'server_test_acc': 0.6487}, 3418.758678866994)
INFO flwr 2023-09-26 01:28:11,965 | server.py:163 | evaluate_round 16: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=3800154)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3800566)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3801013)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3801481)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3801902)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3802356)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3802775)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:28:55,598 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=3803228)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:29:11,118 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3804755)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3804756)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3804757)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3804746)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3804758)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3804754)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3804753)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 01:30:27,990 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-09-26 01:30:28,100 | fed_df_hetero.py:400 | Warm start at round 17
[2m[36m(launch_and_fit pid=3804752)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3899780)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3900097)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3900401)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3900711)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3901437)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3901858)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3902295)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 01:31:12,166 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 01:31:12,190 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 01:31:12,287 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 01:31:12,287 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=3804746)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3804757)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3804754)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3804752)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3804755)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3804753)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3804758)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3804756)[0m Fitting Client 1
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=3902725)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:31:37,685 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.5774524130225182, 'fusion_acc': 0.4941272727272727}, {'fusion_loss': 0.5698195054531098, 'fusion_acc': 0.5568727272727272}, {'fusion_loss': 0.3549477606117725, 'fusion_acc': 0.6482545454545455}]
INFO flwr 2023-09-26 01:31:37,685 | common.py:35 | Avg. local train loss : 2.987668158859015, train acc : 0.964861111111111
INFO flwr 2023-09-26 01:31:44,853 | server.py:116 | fit progress: (17, 5.951470544433594, {'server_test_acc': 0.668}, 3631.647600302)
INFO flwr 2023-09-26 01:31:44,854 | server.py:163 | evaluate_round 17: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=3912045)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3912500)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3912908)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3913348)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3913821)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3914219)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3914586)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 01:32:28,914 | fed_df_hetero.py:270 | Best Server Model Name : resnet20
[2m[36m(launch_and_get_properties pid=3915265)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 01:32:46,407 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3916341)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3916371)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3916344)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3916368)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3916370)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3916338)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:34:07,147 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-09-26 01:34:07,259 | fed_df_hetero.py:400 | Warm start at round 18
[2m[36m(launch_and_fit pid=3916369)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3916372)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=4011370)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=4011799)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4012230)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4012928)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4013424)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=4013858)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4014279)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:34:50,952 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 01:34:51,028 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 01:34:51,089 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 01:34:51,089 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=3916338)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3916341)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3916344)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3916372)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3916370)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3916368)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3916371)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3916369)[0m Fitting Client 7
[2m[36m(launch_and_get_properties pid=4014713)[0m double free or corruption (fasttop)
E0926 01:35:06.663484468 4019921 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
INFO flwr 2023-09-26 01:35:16,105 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.46411094188690183, 'fusion_acc': 0.5516727272727273}, {'fusion_loss': 0.3761171448528767, 'fusion_acc': 0.6780545454545455}, {'fusion_loss': 0.34705245864391326, 'fusion_acc': 0.653818181818182}]
INFO flwr 2023-09-26 01:35:16,105 | common.py:35 | Avg. local train loss : 2.847701394371688, train acc : 0.9770652777777777
INFO flwr 2023-09-26 01:35:23,336 | server.py:116 | fit progress: (18, 4.634497973632812, {'server_test_acc': 0.6869}, 3850.1299611259965)
INFO flwr 2023-09-26 01:35:23,336 | server.py:163 | evaluate_round 18: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=4024317)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=4024725)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4025194)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4025613)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4026033)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=4026468)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=4026898)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 01:36:07,138 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=4027341)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:36:22,891 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4028890)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4028895)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4028872)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4028892)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4028891)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:37:38,911 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-09-26 01:37:39,022 | fed_df_hetero.py:400 | Warm start at round 19
[2m[36m(launch_and_fit pid=4028896)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4028874)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4028893)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4123044)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4123470)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=4123916)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4124330)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4124759)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4125205)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=4125624)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 01:38:22,927 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 01:38:22,990 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 01:38:23,032 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 01:38:23,032 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=4028872)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4028874)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4028891)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4028892)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4028890)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4028893)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4028896)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4028895)[0m Fitting Client 3
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
E0926 01:38:24.907856671 4126651 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_get_properties pid=4126041)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:38:48,309 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.3965327454507351, 'fusion_acc': 0.5533818181818181}, {'fusion_loss': 0.35529821065068246, 'fusion_acc': 0.6657454545454545}, {'fusion_loss': 0.2828344686329365, 'fusion_acc': 0.6145090909090909}]
INFO flwr 2023-09-26 01:38:48,309 | common.py:35 | Avg. local train loss : 2.9322634994052352, train acc : 0.9749777777777778
INFO flwr 2023-09-26 01:38:55,680 | server.py:116 | fit progress: (19, 4.911023400878906, {'server_test_acc': 0.6468}, 4062.474552391999)
INFO flwr 2023-09-26 01:38:55,681 | server.py:163 | evaluate_round 19: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=4135685)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4135983)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=4136297)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=4136590)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4136904)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4137240)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4137549)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-09-26 01:39:39,325 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=4137967)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 01:39:55,160 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4139766)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4139770)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4139767)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4139768)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4139762)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4139760)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4139772)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 01:41:12,843 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-09-26 01:41:12,956 | fed_df_hetero.py:400 | Warm start at round 20
[2m[36m(launch_and_fit pid=4139771)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=46347)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=47801)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=53880)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=59285)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=61715)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=64910)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=68004)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:41:57,229 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 01:41:57,302 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 01:41:57,343 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 01:41:57,343 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=4139762)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4139766)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4139768)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4139760)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4139771)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4139772)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4139767)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4139770)[0m Fitting Client 3
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=68490)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:42:22,441 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.48741154897212985, 'fusion_acc': 0.46976363636363644}, {'fusion_loss': 0.4446349597275257, 'fusion_acc': 0.6529272727272727}, {'fusion_loss': 0.353577651232481, 'fusion_acc': 0.6115454545454545}]
INFO flwr 2023-09-26 01:42:22,442 | common.py:35 | Avg. local train loss : 2.971900122705847, train acc : 0.9718749999999999
INFO flwr 2023-09-26 01:42:29,680 | server.py:116 | fit progress: (20, 5.581643542480469, {'server_test_acc': 0.6293}, 4276.474024286996)
INFO flwr 2023-09-26 01:42:29,680 | server.py:163 | evaluate_round 20: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=93591)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=94013)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=94435)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=94867)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=95580)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=96012)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=96450)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 01:43:13,823 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=96828)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:43:26,055 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=97798)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=97804)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=97807)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=97806)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=97808)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=97805)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=97809)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 01:44:42,824 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-09-26 01:44:42,937 | fed_df_hetero.py:400 | Warm start at round 21
[2m[36m(launch_and_fit pid=97801)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=192640)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=193083)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=193576)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=193995)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=194398)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=194815)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=195237)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 01:45:27,126 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 01:45:27,150 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 01:45:27,229 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 01:45:27,229 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=97806)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=97808)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=97809)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=97804)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=97801)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=97798)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=97805)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=97807)[0m Fitting Client 5
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=195953)[0m malloc_consolidate(): invalid chunk size
E0926 01:45:49.705825648  202373 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
INFO flwr 2023-09-26 01:45:52,461 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.6622397873401642, 'fusion_acc': 0.4184909090909091}, {'fusion_loss': 0.6224561539292336, 'fusion_acc': 0.5455272727272727}, {'fusion_loss': 0.3843434310555458, 'fusion_acc': 0.5632727272727274}]
INFO flwr 2023-09-26 01:45:52,461 | common.py:35 | Avg. local train loss : 2.968085338268429, train acc : 0.9714569444444444
INFO flwr 2023-09-26 01:45:59,821 | server.py:116 | fit progress: (21, 10.813387377929688, {'server_test_acc': 0.5867}, 4486.6150200819975)
INFO flwr 2023-09-26 01:45:59,821 | server.py:163 | evaluate_round 21: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=204772)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=205069)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=205415)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=205833)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=206279)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=206992)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=207395)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:46:44,032 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=207812)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:46:56,157 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=209046)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=209045)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=209049)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=209014)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=209048)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=209050)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:48:13,631 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-09-26 01:48:13,742 | fed_df_hetero.py:400 | Warm start at round 22
[2m[36m(launch_and_fit pid=209047)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=209051)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=303711)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=304128)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=304569)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=304989)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=305417)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=305808)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=306219)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 01:48:57,663 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 01:48:57,715 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 01:48:57,777 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 01:48:57,777 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=209014)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=209047)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=209051)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=209045)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=209046)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=209050)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=209048)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=209049)[0m Fitting Client 5
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=306945)[0m double free or corruption (fasttop)
E0926 01:48:59.923244180 1828608 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
INFO flwr 2023-09-26 01:49:23,053 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.589766012609005, 'fusion_acc': 0.487690909090909}, {'fusion_loss': 0.4979155395030975, 'fusion_acc': 0.6432545454545454}, {'fusion_loss': 0.3546087783277035, 'fusion_acc': 0.6730545454545455}]
INFO flwr 2023-09-26 01:49:23,053 | common.py:35 | Avg. local train loss : 2.915132930129767, train acc : 0.9749027777777778
INFO flwr 2023-09-26 01:49:30,318 | server.py:116 | fit progress: (22, 4.019611401367188, {'server_test_acc': 0.7015}, 4697.112107968998)
INFO flwr 2023-09-26 01:49:30,318 | server.py:163 | evaluate_round 22: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=316410)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=316810)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=317229)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=317631)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=318107)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=318483)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=318863)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 01:50:14,151 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=319182)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 01:50:30,198 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=320796)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=320798)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=320806)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=320805)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=320809)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=320808)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=320804)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:51:45,697 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-09-26 01:51:45,808 | fed_df_hetero.py:400 | Warm start at round 23
[2m[36m(launch_and_fit pid=320802)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=414261)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=415019)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=415449)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=415885)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=416299)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=416708)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=417082)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:52:30,521 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 01:52:30,544 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 01:52:30,623 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 01:52:30,623 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=320796)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=320805)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=320806)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=320798)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=320809)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=320808)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=320802)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=320804)[0m Fitting Client 14
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=417477)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:52:56,086 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.576811224579811, 'fusion_acc': 0.44552727272727277}, {'fusion_loss': 0.5576925792694092, 'fusion_acc': 0.5390909090909091}, {'fusion_loss': 0.33540304386615755, 'fusion_acc': 0.6496545454545455}]
INFO flwr 2023-09-26 01:52:56,087 | common.py:35 | Avg. local train loss : 2.9313496591523296, train acc : 0.974426388888889
INFO flwr 2023-09-26 01:53:03,201 | server.py:116 | fit progress: (23, 5.052977124023437, {'server_test_acc': 0.6822}, 4909.995762783001)
INFO flwr 2023-09-26 01:53:03,202 | server.py:163 | evaluate_round 23: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=425953)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=426251)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=426541)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=427273)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=427792)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=428191)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=428592)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 01:53:47,738 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=428987)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 01:53:59,824 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=430310)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=430306)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=430312)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=430318)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=430311)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:55:22,049 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-09-26 01:55:22,161 | fed_df_hetero.py:400 | Warm start at round 24
[2m[36m(launch_and_fit pid=430320)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=430313)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=430305)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=524991)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=525315)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=525616)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=525980)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=526411)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=526853)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=527281)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:56:06,217 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 01:56:06,299 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 01:56:06,361 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 01:56:06,361 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=430306)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=430305)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=430313)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=430312)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=430318)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=430311)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=430310)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=430320)[0m Fitting Client 13
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=527727)[0m double free or corruption (fasttop)
E0926 01:56:18.471327590  532407 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
INFO flwr 2023-09-26 01:56:31,593 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.6912462150454521, 'fusion_acc': 0.525290909090909}, {'fusion_loss': 0.5681151287555695, 'fusion_acc': 0.7127090909090911}, {'fusion_loss': 0.4626938685774803, 'fusion_acc': 0.6859090909090909}]
INFO flwr 2023-09-26 01:56:31,594 | common.py:35 | Avg. local train loss : 2.7283975395374, train acc : 0.9842458333333334
INFO flwr 2023-09-26 01:56:38,856 | server.py:116 | fit progress: (24, 3.8527918701171875, {'server_test_acc': 0.7223}, 5125.650695698998)
INFO flwr 2023-09-26 01:56:38,857 | server.py:163 | evaluate_round 24: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=539995)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=541677)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=543851)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=547177)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=551116)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=556805)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=560958)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 01:57:23,006 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=564744)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:57:38,789 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=573392)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=573390)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=573322)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=573380)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=573410)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=573386)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 01:58:52,080 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-09-26 01:58:52,192 | fed_df_hetero.py:400 | Warm start at round 25
[2m[36m(launch_and_fit pid=573391)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=573412)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=676412)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=676893)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=677362)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=677829)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=678297)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=678790)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=679599)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 01:59:36,881 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 01:59:36,907 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 01:59:36,968 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 01:59:36,968 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=573392)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=573410)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=573380)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=573390)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=573391)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=573412)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=573322)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=573386)[0m Fitting Client 17
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=680033)[0m double free or corruption (fasttop)
E0926 01:59:47.193547676  682900 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-26 02:00:02,569 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.4658611966073513, 'fusion_acc': 0.47258181818181816}, {'fusion_loss': 0.46322608590126035, 'fusion_acc': 0.4885454545454545}, {'fusion_loss': 0.25879187253117564, 'fusion_acc': 0.6026363636363636}]
INFO flwr 2023-09-26 02:00:02,570 | common.py:35 | Avg. local train loss : 2.9438824256882072, train acc : 0.973475
INFO flwr 2023-09-26 02:00:09,760 | server.py:116 | fit progress: (25, 7.1955384765625, {'server_test_acc': 0.6141}, 5336.554592633998)
INFO flwr 2023-09-26 02:00:09,761 | server.py:163 | evaluate_round 25: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=688827)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=689134)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=689591)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=690091)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=690573)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=691091)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=691583)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 02:00:54,232 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=692075)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 02:01:06,519 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=693874)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=693899)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=693887)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=693901)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 02:02:19,054 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-09-26 02:02:19,167 | fed_df_hetero.py:400 | Warm start at round 26
[2m[36m(launch_and_fit pid=693900)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=693897)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=693898)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=693886)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=788747)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=789772)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=790141)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=790482)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=790843)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=791183)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=791677)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 02:03:03,682 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 02:03:03,708 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 02:03:03,787 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 02:03:03,787 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=693874)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=693901)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=693899)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=693886)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=693898)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=693897)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=693900)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=693887)[0m Fitting Client 6
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=792200)[0m malloc_consolidate(): invalid chunk size
E0926 02:03:07.131759140  794068 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-26 02:03:29,169 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.7069780139923095, 'fusion_acc': 0.4475636363636364}, {'fusion_loss': 0.6287495291233063, 'fusion_acc': 0.5784363636363636}, {'fusion_loss': 0.40834178164601326, 'fusion_acc': 0.6221636363636364}]
INFO flwr 2023-09-26 02:03:29,169 | common.py:35 | Avg. local train loss : 2.950496787391603, train acc : 0.9712138888888889
INFO flwr 2023-09-26 02:03:36,327 | server.py:116 | fit progress: (26, 7.255113293457031, {'server_test_acc': 0.6553}, 5543.121152369)
INFO flwr 2023-09-26 02:03:36,327 | server.py:163 | evaluate_round 26: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=802027)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=802532)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=803066)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=803887)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=804401)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=804939)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=805455)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 02:04:21,228 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=805927)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 02:04:33,351 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=807166)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=807167)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=807173)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=807169)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=807174)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=807175)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 02:05:52,778 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-09-26 02:05:52,890 | fed_df_hetero.py:400 | Warm start at round 27
[2m[36m(launch_and_fit pid=807171)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=807172)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=902807)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=903341)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=903864)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=904401)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=904909)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=905450)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=906300)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 02:06:37,479 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 02:06:37,556 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 02:06:37,617 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 02:06:37,617 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=807171)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=807173)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=807172)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=807174)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=807166)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=807175)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=807167)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=807169)[0m Fitting Client 18
[2m[36m(launch_and_get_properties pid=906830)[0m malloc_consolidate(): invalid chunk size
E0926 02:06:48.340773279  910063 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-26 02:07:02,981 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.7363997218608856, 'fusion_acc': 0.5151636363636363}, {'fusion_loss': 0.5809592463374138, 'fusion_acc': 0.7097818181818183}, {'fusion_loss': 0.4143832073807716, 'fusion_acc': 0.7248909090909091}]
INFO flwr 2023-09-26 02:07:02,981 | common.py:35 | Avg. local train loss : 2.7735608016140763, train acc : 0.9827499999999999
INFO flwr 2023-09-26 02:07:10,311 | server.py:116 | fit progress: (27, 3.775071057128906, {'server_test_acc': 0.7352}, 5757.104929918998)
INFO flwr 2023-09-26 02:07:10,311 | server.py:163 | evaluate_round 27: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=916602)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=916964)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=917360)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=917734)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=918115)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=918488)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=919044)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 02:07:54,534 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=919571)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 02:08:10,424 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=921552)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=921549)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=921551)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=921548)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=921567)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=921568)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-26 02:09:27,697 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-09-26 02:09:27,810 | fed_df_hetero.py:400 | Warm start at round 28
[2m[36m(launch_and_fit pid=921550)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=921546)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1017799)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1018147)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1018523)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1018897)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1019262)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1020004)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1020351)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 02:10:11,950 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 02:10:11,994 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 02:10:12,075 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 02:10:12,075 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=921550)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=921548)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=921551)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=921568)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=921567)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=921549)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=921546)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=921552)[0m Fitting Client 4
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=1020810)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 02:10:37,575 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.6755183187127113, 'fusion_acc': 0.5174363636363636}, {'fusion_loss': 0.6289270436167717, 'fusion_acc': 0.6498909090909092}, {'fusion_loss': 0.37512191209197043, 'fusion_acc': 0.6917636363636364}]
INFO flwr 2023-09-26 02:10:37,575 | common.py:35 | Avg. local train loss : 2.846641584672034, train acc : 0.9759972222222222
INFO flwr 2023-09-26 02:10:44,896 | server.py:116 | fit progress: (28, 5.919712658691406, {'server_test_acc': 0.7091}, 5971.689872905001)
INFO flwr 2023-09-26 02:10:44,896 | server.py:163 | evaluate_round 28: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=1031093)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1031607)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1032182)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1032717)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1033245)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1033786)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1034319)[0m double free or corruption (fasttop)
INFO flwr 2023-09-26 02:11:29,608 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=1035185)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 02:11:45,276 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1037010)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1037035)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1037033)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1037034)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1037037)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1037014)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 02:13:02,168 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-09-26 02:13:02,280 | fed_df_hetero.py:400 | Warm start at round 29
[2m[36m(launch_and_fit pid=1037036)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1037039)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1142382)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1144542)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1153112)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1157176)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1158121)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1158673)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1160555)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 02:13:46,638 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 02:13:46,683 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 02:13:46,763 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 02:13:46,764 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=1037037)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1037035)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1037034)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1037014)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1037033)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1037010)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1037036)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1037039)[0m Fitting Client 9
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=1165732)[0m malloc_consolidate(): invalid chunk size
E0926 02:14:00.573540433  911304 chttp2_transport.cc:1079]             ipv4:145.136.62.34:41555: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-26 02:14:12,424 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.6244665900468827, 'fusion_acc': 0.4777454545454546}, {'fusion_loss': 0.600820240676403, 'fusion_acc': 0.6107818181818182}, {'fusion_loss': 0.3521854175329208, 'fusion_acc': 0.6577636363636364}]
INFO flwr 2023-09-26 02:14:12,424 | common.py:35 | Avg. local train loss : 2.7699804893694817, train acc : 0.9820847222222221
INFO flwr 2023-09-26 02:14:19,719 | server.py:116 | fit progress: (29, 5.775686889648438, {'server_test_acc': 0.6945}, 6186.513009056995)
INFO flwr 2023-09-26 02:14:19,719 | server.py:163 | evaluate_round 29: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=1185269)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1186356)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1186767)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1187198)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1187563)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1187927)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1188358)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 02:15:03,788 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=1188731)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 02:15:19,430 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1190167)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1190150)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1190147)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1190142)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1190166)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1190146)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1190145)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-26 02:16:34,181 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-09-26 02:16:34,292 | fed_df_hetero.py:400 | Warm start at round 30
[2m[36m(launch_and_fit pid=1190151)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1285836)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1286364)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1286873)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1287418)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1287933)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1288398)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1288811)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 02:17:18,553 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-26 02:17:18,577 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-26 02:17:18,658 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-26 02:17:18,658 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=1190150)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1190146)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1190147)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1190166)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1190167)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1190145)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1190142)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1190151)[0m Fitting Client 8
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=1289215)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-26 02:17:44,272 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.770190633893013, 'fusion_acc': 0.49105454545454547}, {'fusion_loss': 0.6773606450557709, 'fusion_acc': 0.6249636363636364}, {'fusion_loss': 0.4417572301030159, 'fusion_acc': 0.6653272727272728}]
INFO flwr 2023-09-26 02:17:44,273 | common.py:35 | Avg. local train loss : 2.844519296847284, train acc : 0.9796166666666666
INFO flwr 2023-09-26 02:17:51,460 | server.py:116 | fit progress: (30, 4.901893420410156, {'server_test_acc': 0.6897}, 6398.253988230994)
INFO flwr 2023-09-26 02:17:51,460 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-09-26 02:17:51,460 | server.py:144 | FL finished in 6398.254383437001
INFO flwr 2023-09-26 02:17:51,461 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-09-26 02:17:51,462 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-09-26 02:17:51,462 | app.py:204 | app_fit: losses_centralized [(0, 3.7793668823242186), (1, 3.480742150878906), (2, 2.5099783203125), (3, 3.5162487854003905), (4, 3.7858687744140624), (5, 3.470958093261719), (6, 4.435352136230469), (7, 3.265357989501953), (8, 3.103964959716797), (9, 4.302023095703125), (10, 4.466257470703125), (11, 3.8037269165039063), (12, 2.73856884765625), (13, 3.905578369140625), (14, 6.9386432861328124), (15, 7.57085703125), (16, 5.090053894042969), (17, 5.951470544433594), (18, 4.634497973632812), (19, 4.911023400878906), (20, 5.581643542480469), (21, 10.813387377929688), (22, 4.019611401367188), (23, 5.052977124023437), (24, 3.8527918701171875), (25, 7.1955384765625), (26, 7.255113293457031), (27, 3.775071057128906), (28, 5.919712658691406), (29, 5.775686889648438), (30, 4.901893420410156)]
INFO flwr 2023-09-26 02:17:51,462 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.1), (1, 0.3312), (2, 0.495), (3, 0.4803), (4, 0.5079), (5, 0.5963), (6, 0.5882), (7, 0.6292), (8, 0.6554), (9, 0.6535), (10, 0.6583), (11, 0.6259), (12, 0.697), (13, 0.6597), (14, 0.6405), (15, 0.6201), (16, 0.6487), (17, 0.668), (18, 0.6869), (19, 0.6468), (20, 0.6293), (21, 0.5867), (22, 0.7015), (23, 0.6822), (24, 0.7223), (25, 0.6141), (26, 0.6553), (27, 0.7352), (28, 0.7091), (29, 0.6945), (30, 0.6897)]}
double free or corruption (fasttop)
srun: error: gcn34: task 0: Aborted
srun: Terminating StepId=3926529.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3926529
Cluster: snellius
User/Group: sunnys/sunnys
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 02:33:32
CPU Efficiency: 7.77% of 1-08:55:12 core-walltime
Job Wall-clock time: 01:49:44
Memory Utilized: 26.62 GB
Memory Efficiency: 22.19% of 120.00 GB
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
