-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:20000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:100.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:organamnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:10000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:9
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:0.25
CONFIDENCE_THRESHOLD:0.5
CONFIDENCE_STRATEGY:bottom
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:True
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=20000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3357205/1692172431_816115465', seed=84, img_per_thread=1111)
will save 20000 patches in /scratch-local/sunnys.3357205/1692172431_816115465/single_img_crops/crops
20000 took 0.15min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-16 09:54:16,499 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-16 09:54:16,500 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3357205/1692172431_816115465/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3357205/1692172431_816115465/cifar-10-python.tar.gz to /scratch-local/sunnys.3357205/1692172431_816115465
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=100.0, 10 classes): [225 194 247 272 217 251 256 333 258 247]
INFO flwr 2023-08-16 09:54:34,751 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-16 09:54:37,260	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-16 09:54:38,199 | app.py:179 | Flower VCE: Ray initialized with resources: {'accelerator_type:A100': 1.0, 'object_store_memory': 61847529062.0, 'GPU': 1.0, 'node:145.136.62.38': 1.0, 'memory': 103079215104.0, 'CPU': 18.0}
INFO flwr 2023-08-16 09:54:38,199 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-16 09:54:38,199 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-16 09:54:38,199 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-16 09:54:49,850 | server.py:91 | initial parameters (loss, other metrics): 2.319245477294922, {'server_test_acc': 0.0811}
INFO flwr 2023-08-16 09:54:49,850 | server.py:101 | FL starting
DEBUG flwr 2023-08-16 09:54:54,863 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 09:55:43,336 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-16 09:55:43,548 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-16 09:55:43,674 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2691438)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2691436)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2691434)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2691435)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2691437)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2691433)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2691439)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2691432)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2691437)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2691438)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2691434)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2691436)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2691439)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2691432)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2691435)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2691433)[0m malloc_consolidate(): invalid chunk size
E0816 09:55:45.670089549 2739752 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-08-16 09:56:16,707 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 09:56:16,708 | fed_df.py:547 | Average fusion training loss : 0.021840892419219018, val accuracy : 0.42151999999999995, best val accuracy : 0.4446
INFO flwr 2023-08-16 09:56:16,710 | common.py:35 | Avg. local train loss : 8.841866825520992, train acc : 0.3779166666666667
INFO flwr 2023-08-16 09:56:19,076 | server.py:116 | fit progress: (1, 1.5128369262695311, {'server_test_acc': 0.4535}, 89.22549796500243)
INFO flwr 2023-08-16 09:56:19,076 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-16 09:56:24,050 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2765127)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 09:57:11,461 | server.py:229 | fit_round 2 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2765129)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 09:57:11,737 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2765127)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2765128)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2765129)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2765130)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2765131)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2765133)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2765132)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2765134)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2765130)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2765133)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2765132)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2765131)[0m malloc_consolidate(): invalid chunk size
E0816 09:57:12.833023527 2739851 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=2765128)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2765134)[0m double free or corruption (fasttop)
E0816 09:57:22.388185064 2820383 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-08-16 09:57:39,610 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 09:57:39,610 | fed_df.py:547 | Average fusion training loss : 0.024252162974327803, val accuracy : 0.49504000000000004, best val accuracy : 0.53
INFO flwr 2023-08-16 09:57:39,612 | common.py:35 | Avg. local train loss : 7.224413350224494, train acc : 0.5552444444444444
INFO flwr 2023-08-16 09:57:42,030 | server.py:116 | fit progress: (2, 1.4916029907226562, {'server_test_acc': 0.5344}, 172.1794368819974)
INFO flwr 2023-08-16 09:57:42,030 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-16 09:57:46,960 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2838338)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 09:58:34,289 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-16 09:58:34,565 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2838337)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2838341)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2838340)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2838338)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2838339)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2838343)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2838342)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2838344)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2838343)[0m malloc_consolidate(): invalid chunk size
E0816 09:58:35.193214801 2820792 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
[2m[36m(launch_and_fit pid=2838341)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2838339)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2838337)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2838342)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2838344)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2838340)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 09:59:02,691 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 09:59:02,691 | fed_df.py:547 | Average fusion training loss : 0.012489779442548752, val accuracy : 0.54676, best val accuracy : 0.5652
INFO flwr 2023-08-16 09:59:02,693 | common.py:35 | Avg. local train loss : 6.753831271082163, train acc : 0.6065055555555556
INFO flwr 2023-08-16 09:59:05,101 | server.py:116 | fit progress: (3, 1.4368529357910156, {'server_test_acc': 0.5619}, 255.2513522490044)
INFO flwr 2023-08-16 09:59:05,102 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-16 09:59:10,089 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2911917)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2911922)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 09:59:56,914 | server.py:229 | fit_round 4 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2911918)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 09:59:57,192 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2911917)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2911922)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2911923)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2911921)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2911918)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2911920)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2911919)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2911924)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2911923)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2911921)[0m malloc_consolidate(): invalid chunk size
E0816 09:59:58.355125212 2885721 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=2911924)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2911920)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2911919)[0m double free or corruption (fasttop)
E0816 10:00:12.938124236 2959813 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-08-16 10:00:25,505 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:00:25,506 | fed_df.py:547 | Average fusion training loss : 0.010837718773633242, val accuracy : 0.5814, best val accuracy : 0.6034
INFO flwr 2023-08-16 10:00:25,508 | common.py:35 | Avg. local train loss : 6.374913282692432, train acc : 0.6472749999999999
INFO flwr 2023-08-16 10:00:27,954 | server.py:116 | fit progress: (4, 1.4065710388183594, {'server_test_acc': 0.603}, 338.1036312429933)
INFO flwr 2023-08-16 10:00:27,954 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-16 10:00:32,877 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2985498)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:01:20,179 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-16 10:01:20,388 | fed_df.py:365 | Warm start at round 5
[2m[36m(launch_and_fit pid=2985496)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 10:01:20,514 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2985498)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2985497)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2985499)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2985496)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2985500)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2985501)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2985502)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2985503)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2985500)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2985502)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2985501)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2985499)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2985497)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2985503)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:01:48,914 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:01:48,914 | fed_df.py:547 | Average fusion training loss : 0.012675840441137553, val accuracy : 0.62416, best val accuracy : 0.6422
INFO flwr 2023-08-16 10:01:48,916 | common.py:35 | Avg. local train loss : 6.118090042099357, train acc : 0.6755138888888889
INFO flwr 2023-08-16 10:01:51,367 | server.py:116 | fit progress: (5, 1.225176318359375, {'server_test_acc': 0.6436}, 421.51649449398974)
INFO flwr 2023-08-16 10:01:51,367 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-16 10:01:56,322 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3059149)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3059151)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:02:43,401 | server.py:229 | fit_round 6 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3059154)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3059159)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:02:43,682 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3059151)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3059149)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3059155)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3059158)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3059157)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3059159)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3059156)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3059154)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3059156)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3059157)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3059158)[0m malloc_consolidate(): invalid chunk size
E0816 10:02:44.663234720 2972056 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=3059155)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 10:03:12,089 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:03:12,089 | fed_df.py:547 | Average fusion training loss : 0.00835331467911601, val accuracy : 0.6542800000000001, best val accuracy : 0.6602
INFO flwr 2023-08-16 10:03:12,091 | common.py:35 | Avg. local train loss : 5.571151261776686, train acc : 0.7289388888888889
INFO flwr 2023-08-16 10:03:14,540 | server.py:116 | fit progress: (6, 1.259322348022461, {'server_test_acc': 0.6493}, 504.6898952659976)
INFO flwr 2023-08-16 10:03:14,540 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-16 10:03:19,514 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3132502)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:04:06,462 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-16 10:04:06,743 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3132502)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3132504)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3132503)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3132508)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3132506)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3132505)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3132501)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3132507)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3132503)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3132508)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3132507)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3132505)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3132504)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3132506)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3132501)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:04:40,419 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:04:40,419 | fed_df.py:547 | Average fusion training loss : 0.010401802694424986, val accuracy : 0.64864, best val accuracy : 0.655
INFO flwr 2023-08-16 10:04:40,421 | common.py:35 | Avg. local train loss : 5.513135113567114, train acc : 0.7359916666666666
INFO flwr 2023-08-16 10:04:42,876 | server.py:116 | fit progress: (7, 1.2875899505615234, {'server_test_acc': 0.6553}, 593.0257734619954)
INFO flwr 2023-08-16 10:04:42,876 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-16 10:04:47,846 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3206095)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3206101)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3206106)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:05:35,319 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-16 10:05:35,596 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3206095)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3206097)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3206100)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3206102)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3206101)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3206105)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3206104)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3206106)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3206104)[0m double free or corruption (fasttop)
E0816 10:05:36.350025139 3253201 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=3206100)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3206102)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3206097)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3206105)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:06:03,932 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:06:03,932 | fed_df.py:547 | Average fusion training loss : 0.007072795411571861, val accuracy : 0.64524, best val accuracy : 0.6564
INFO flwr 2023-08-16 10:06:03,934 | common.py:35 | Avg. local train loss : 5.41954814903438, train acc : 0.7462972222222222
INFO flwr 2023-08-16 10:06:06,383 | server.py:116 | fit progress: (8, 1.266434341430664, {'server_test_acc': 0.6574}, 676.5329779110034)
INFO flwr 2023-08-16 10:06:06,383 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-16 10:06:11,491 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3279736)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:06:58,709 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-16 10:06:58,988 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3279742)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3279736)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3279738)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3279740)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3279741)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3279742)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3279739)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3279735)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3279737)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3279735)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3279737)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3279739)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3279741)[0m malloc_consolidate(): invalid chunk size
E0816 10:07:00.275962318 3253625 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=3279740)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3279738)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:07:27,411 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:07:27,412 | fed_df.py:547 | Average fusion training loss : 0.010464840257540345, val accuracy : 0.66052, best val accuracy : 0.6732
INFO flwr 2023-08-16 10:07:27,414 | common.py:35 | Avg. local train loss : 5.376797349005938, train acc : 0.75105
INFO flwr 2023-08-16 10:07:29,853 | server.py:116 | fit progress: (9, 1.258098483276367, {'server_test_acc': 0.6686}, 760.0029069340089)
INFO flwr 2023-08-16 10:07:29,853 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-16 10:07:34,793 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 10:08:22,185 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-16 10:08:22,394 | fed_df.py:365 | Warm start at round 10
[2m[36m(launch_and_fit pid=3353308)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3353311)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 10:08:22,522 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3353308)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3353303)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3353305)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3353307)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3353304)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3353309)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3353311)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3353310)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3353305)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3353307)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3353309)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3353304)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3353303)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3353310)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:08:56,008 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:08:56,008 | fed_df.py:547 | Average fusion training loss : 0.012858363328501583, val accuracy : 0.68692, best val accuracy : 0.6928
INFO flwr 2023-08-16 10:08:56,010 | common.py:35 | Avg. local train loss : 5.33588867969811, train acc : 0.7541638888888889
INFO flwr 2023-08-16 10:08:58,502 | server.py:116 | fit progress: (10, 1.195894122314453, {'server_test_acc': 0.6846}, 848.652013199986)
INFO flwr 2023-08-16 10:08:58,502 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-16 10:09:03,509 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3426890)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3426886)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:09:50,774 | server.py:229 | fit_round 11 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3426895)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:09:51,055 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3426886)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3426890)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3426891)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3426888)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3426887)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3426896)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3426897)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3426895)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3426888)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3426896)[0m malloc_consolidate(): invalid chunk size
E0816 10:09:52.017950229 3486686 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=3426887)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3426897)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3426891)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:10:20,097 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:10:20,097 | fed_df.py:547 | Average fusion training loss : 0.008747853687033057, val accuracy : 0.6843199999999999, best val accuracy : 0.6936
INFO flwr 2023-08-16 10:10:20,100 | common.py:35 | Avg. local train loss : 5.094213069602848, train acc : 0.7768222222222221
INFO flwr 2023-08-16 10:10:22,593 | server.py:116 | fit progress: (11, 1.260543881225586, {'server_test_acc': 0.6942}, 932.7430560549838)
INFO flwr 2023-08-16 10:10:22,593 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-16 10:10:27,665 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3524563)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3524567)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3524561)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:11:15,740 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-16 10:11:16,017 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3524567)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3524340)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3524563)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3524561)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3524562)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3524566)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3524565)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3524564)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3524562)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3524340)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3524565)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3524564)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3524566)[0m malloc_consolidate(): invalid chunk size
E0816 10:11:19.374527617 3574375 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
INFO flwr 2023-08-16 10:11:44,475 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:11:44,475 | fed_df.py:547 | Average fusion training loss : 0.007094208655878902, val accuracy : 0.6908399999999999, best val accuracy : 0.7028
INFO flwr 2023-08-16 10:11:44,477 | common.py:35 | Avg. local train loss : 5.108737068250775, train acc : 0.7764694444444444
INFO flwr 2023-08-16 10:11:46,948 | server.py:116 | fit progress: (12, 1.2577306549072265, {'server_test_acc': 0.6971}, 1017.0980044940079)
INFO flwr 2023-08-16 10:11:46,948 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-16 10:11:51,868 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3598820)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:12:38,732 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-16 10:12:39,011 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3598820)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3598821)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3598824)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3598829)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3598826)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3598827)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3598823)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3598828)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3598826)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3598829)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3598824)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3598823)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3598821)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3598827)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3598828)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:13:07,924 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:13:07,924 | fed_df.py:547 | Average fusion training loss : 0.0064042756306007505, val accuracy : 0.68568, best val accuracy : 0.6976
INFO flwr 2023-08-16 10:13:07,926 | common.py:35 | Avg. local train loss : 5.033841028437017, train acc : 0.7841444444444444
INFO flwr 2023-08-16 10:13:10,391 | server.py:116 | fit progress: (13, 1.2492872833251953, {'server_test_acc': 0.7008}, 1100.5412427049887)
INFO flwr 2023-08-16 10:13:10,392 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-16 10:13:15,321 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3672218)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3672220)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:14:02,556 | server.py:229 | fit_round 14 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3672221)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 10:14:02,834 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3672218)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3672219)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3672222)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3672220)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3672214)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3672217)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3672216)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3672221)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3672219)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3672216)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3672222)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3672217)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3672214)[0m malloc_consolidate(): invalid chunk size
E0816 10:14:05.582977233 3720404 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
INFO flwr 2023-08-16 10:14:31,463 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:14:31,464 | fed_df.py:547 | Average fusion training loss : 0.008671772066503764, val accuracy : 0.6789999999999999, best val accuracy : 0.6878
INFO flwr 2023-08-16 10:14:31,466 | common.py:35 | Avg. local train loss : 5.075166642293334, train acc : 0.7819916666666666
INFO flwr 2023-08-16 10:14:33,904 | server.py:116 | fit progress: (14, 1.2559979431152344, {'server_test_acc': 0.6875}, 1184.0539202000073)
INFO flwr 2023-08-16 10:14:33,904 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-16 10:14:39,050 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3745743)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:15:26,105 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-16 10:15:26,316 | fed_df.py:365 | Warm start at round 15
[2m[36m(launch_and_fit pid=3745745)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:15:26,443 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3745743)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3745747)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3745749)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3745745)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3745748)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3745750)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3745752)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3745751)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3745750)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3745751)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3745747)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3745749)[0m double free or corruption (fasttop)
E0816 10:15:27.700563697 3792976 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=3745748)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3745752)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:15:54,937 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:15:54,937 | fed_df.py:547 | Average fusion training loss : 0.011772132164798678, val accuracy : 0.70712, best val accuracy : 0.7172
INFO flwr 2023-08-16 10:15:54,939 | common.py:35 | Avg. local train loss : 5.06435330659151, train acc : 0.7809499999999999
INFO flwr 2023-08-16 10:15:57,395 | server.py:116 | fit progress: (15, 1.2540185607910157, {'server_test_acc': 0.7108}, 1267.5451565889816)
INFO flwr 2023-08-16 10:15:57,396 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-16 10:16:02,391 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3819382)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:16:49,733 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-16 10:16:50,010 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3819382)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3819386)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3819384)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3819385)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3819398)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3819395)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3819397)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3819396)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3819395)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3819397)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3819396)[0m double free or corruption (fasttop)
E0816 10:16:50.876230651 3793625 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=3819386)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3819384)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3819385)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3819398)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:17:18,702 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:17:18,702 | fed_df.py:547 | Average fusion training loss : 0.004984465226531029, val accuracy : 0.71644, best val accuracy : 0.723
INFO flwr 2023-08-16 10:17:18,704 | common.py:35 | Avg. local train loss : 4.826548817008734, train acc : 0.8039833333333333
INFO flwr 2023-08-16 10:17:21,178 | server.py:116 | fit progress: (16, 1.2806758972167969, {'server_test_acc': 0.7155}, 1351.3277686130023)
INFO flwr 2023-08-16 10:17:21,178 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-16 10:17:26,165 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3892911)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3892910)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:18:13,729 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-16 10:18:14,009 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3892917)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3892911)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3892910)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3892914)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3892918)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3892915)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3892916)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3892912)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3892917)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3892914)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3892916)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3892915)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3892918)[0m double free or corruption (fasttop)
E0816 10:18:15.145102455 3940181 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=3892912)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:18:42,495 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:18:42,495 | fed_df.py:547 | Average fusion training loss : 0.006345370097085834, val accuracy : 0.71452, best val accuracy : 0.719
INFO flwr 2023-08-16 10:18:42,497 | common.py:35 | Avg. local train loss : 4.857396453246475, train acc : 0.8024583333333333
INFO flwr 2023-08-16 10:18:44,969 | server.py:116 | fit progress: (17, 1.2754174377441405, {'server_test_acc': 0.7099}, 1435.1184556410008)
INFO flwr 2023-08-16 10:18:44,969 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-16 10:18:49,886 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3966292)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3966300)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3966295)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:19:37,221 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-16 10:19:37,500 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3966292)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3966294)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3966297)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3966296)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3966295)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3966298)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3966300)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3966299)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3966294)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3966299)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3966297)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3966298)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3966296)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:20:11,051 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:20:11,052 | fed_df.py:547 | Average fusion training loss : 0.0064128465745598075, val accuracy : 0.7041600000000001, best val accuracy : 0.7088
INFO flwr 2023-08-16 10:20:11,054 | common.py:35 | Avg. local train loss : 4.838101292029023, train acc : 0.80405
INFO flwr 2023-08-16 10:20:13,538 | server.py:116 | fit progress: (18, 1.2570561920166015, {'server_test_acc': 0.7059}, 1523.6877479550021)
INFO flwr 2023-08-16 10:20:13,538 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-16 10:20:18,485 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4039689)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:21:05,556 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-16 10:21:05,836 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4039689)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4039686)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4039687)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4039691)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4039695)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4039692)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4039693)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4039694)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4039695)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4039686)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4039691)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4039687)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4039693)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4039692)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4039694)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 10:21:34,530 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:21:34,530 | fed_df.py:547 | Average fusion training loss : 0.005218773832544685, val accuracy : 0.70344, best val accuracy : 0.7104
INFO flwr 2023-08-16 10:21:34,532 | common.py:35 | Avg. local train loss : 4.882440433651208, train acc : 0.7994055555555556
INFO flwr 2023-08-16 10:21:37,118 | server.py:116 | fit progress: (19, 1.282286929321289, {'server_test_acc': 0.711}, 1607.267840244982)
INFO flwr 2023-08-16 10:21:37,118 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-16 10:21:42,104 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4113273)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4113279)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:22:28,980 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-16 10:22:29,190 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-16 10:22:29,337 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4113270)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4113273)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4113276)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4113280)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=4113279)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4113275)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4113277)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4113278)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4113270)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4113275)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4113276)[0m malloc_consolidate(): invalid chunk size
E0816 10:22:30.398815049 3940405 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=4113277)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4113280)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4113278)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:22:57,881 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:22:57,882 | fed_df.py:547 | Average fusion training loss : 0.013009387739002705, val accuracy : 0.70472, best val accuracy : 0.7128
INFO flwr 2023-08-16 10:22:57,884 | common.py:35 | Avg. local train loss : 4.901412089541555, train acc : 0.7986222222222221
INFO flwr 2023-08-16 10:23:00,345 | server.py:116 | fit progress: (20, 1.2742237579345703, {'server_test_acc': 0.7142}, 1690.4945895819983)
INFO flwr 2023-08-16 10:23:00,345 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-16 10:23:05,332 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4186835)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4186840)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4186844)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:23:52,837 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-16 10:23:53,116 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4186835)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4186838)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4186841)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4186840)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4186842)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4186839)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4186843)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4186844)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4186838)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4186843)[0m double free or corruption (fasttop)
E0816 10:23:54.078567379   41027 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=4186839)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4186841)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4186842)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:24:21,802 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:24:21,802 | fed_df.py:547 | Average fusion training loss : 0.004291789632290602, val accuracy : 0.70856, best val accuracy : 0.7144
INFO flwr 2023-08-16 10:24:21,804 | common.py:35 | Avg. local train loss : 4.685949923470616, train acc : 0.8199305555555556
INFO flwr 2023-08-16 10:24:24,294 | server.py:116 | fit progress: (21, 1.3130491119384766, {'server_test_acc': 0.7261}, 1774.4440441940096)
INFO flwr 2023-08-16 10:24:24,294 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-16 10:24:29,286 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=67307)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=67308)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=67309)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:25:17,000 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-16 10:25:17,282 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=67307)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=67308)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=67312)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=67309)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=67310)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=67314)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=67313)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=67311)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=67313)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=67312)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=67310)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=67314)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=67311)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:25:46,125 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:25:46,126 | fed_df.py:547 | Average fusion training loss : 0.006959654396399856, val accuracy : 0.7114800000000001, best val accuracy : 0.7158
INFO flwr 2023-08-16 10:25:46,128 | common.py:35 | Avg. local train loss : 4.753872208297252, train acc : 0.8124999999999999
INFO flwr 2023-08-16 10:25:48,592 | server.py:116 | fit progress: (22, 1.3005873779296875, {'server_test_acc': 0.7209}, 1858.7422659950098)
INFO flwr 2023-08-16 10:25:48,593 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-16 10:25:53,608 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=160880)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:26:40,572 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-16 10:26:40,850 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=160880)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=160882)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=160884)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=160885)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=160886)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=160887)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=160889)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=160888)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=160882)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=160887)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=160888)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=160884)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=160885)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=160889)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=160886)[0m malloc_consolidate(): invalid chunk size
E0816 10:26:43.153890565   41431 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 10:27:09,514 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:27:09,514 | fed_df.py:547 | Average fusion training loss : 0.006126341097056866, val accuracy : 0.71696, best val accuracy : 0.7252
INFO flwr 2023-08-16 10:27:09,516 | common.py:35 | Avg. local train loss : 4.739204458892345, train acc : 0.8143527777777776
INFO flwr 2023-08-16 10:27:11,979 | server.py:116 | fit progress: (23, 1.2872470245361327, {'server_test_acc': 0.7202}, 1942.1286089330097)
INFO flwr 2023-08-16 10:27:11,979 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-16 10:27:17,024 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=239785)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:28:04,251 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-16 10:28:04,553 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=239785)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=239789)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=239788)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=239794)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=239790)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=239791)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=239792)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=239793)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=239788)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=239789)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=239791)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=239794)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=239793)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=239790)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=239792)[0m malloc_consolidate(): invalid chunk size
E0816 10:28:06.422852558  215065 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 10:28:33,307 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:28:33,307 | fed_df.py:547 | Average fusion training loss : 0.005791307388804853, val accuracy : 0.7231200000000001, best val accuracy : 0.7278
INFO flwr 2023-08-16 10:28:33,309 | common.py:35 | Avg. local train loss : 4.754028813913464, train acc : 0.813911111111111
INFO flwr 2023-08-16 10:28:35,805 | server.py:116 | fit progress: (24, 1.262102471923828, {'server_test_acc': 0.7261}, 2025.9550576639886)
INFO flwr 2023-08-16 10:28:35,805 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-16 10:28:41,046 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=313297)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:29:27,538 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-16 10:29:27,752 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-16 10:29:27,901 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=313297)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=313300)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=313299)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=313304)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=313305)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=313306)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=313307)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=313303)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=313299)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=313304)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=313303)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=313306)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=313307)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=313305)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=313300)[0m malloc_consolidate(): invalid chunk size
E0816 10:29:30.836984194  288125 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 10:29:56,651 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:29:56,652 | fed_df.py:547 | Average fusion training loss : 0.012329265777021646, val accuracy : 0.72188, best val accuracy : 0.731
INFO flwr 2023-08-16 10:29:56,654 | common.py:35 | Avg. local train loss : 4.762909185513854, train acc : 0.8125138888888889
INFO flwr 2023-08-16 10:29:59,157 | server.py:116 | fit progress: (25, 1.3315126312255858, {'server_test_acc': 0.7272}, 2109.306409790006)
INFO flwr 2023-08-16 10:29:59,157 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-16 10:30:04,185 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=386852)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:30:52,246 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-16 10:30:52,525 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=386844)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=386847)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=386848)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=386854)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=386853)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=386846)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=386845)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=386852)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=386848)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=386847)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=386854)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=386846)[0m malloc_consolidate(): invalid chunk size
E0816 10:30:53.545068467  362573 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=386853)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=386844)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=386845)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 10:31:21,435 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:31:21,435 | fed_df.py:547 | Average fusion training loss : 0.005060552669689059, val accuracy : 0.72628, best val accuracy : 0.7366
INFO flwr 2023-08-16 10:31:21,437 | common.py:35 | Avg. local train loss : 4.6171596277505165, train acc : 0.8270666666666667
INFO flwr 2023-08-16 10:31:23,913 | server.py:116 | fit progress: (26, 1.3402845153808594, {'server_test_acc': 0.7251}, 2194.0630122669972)
INFO flwr 2023-08-16 10:31:23,913 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-16 10:31:28,995 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=460685)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:32:15,761 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-16 10:32:16,067 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=460685)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=460684)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=460689)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=460691)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=460690)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=460692)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=460694)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=460693)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=460692)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=460689)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=460691)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=460690)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=460694)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=460693)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=460684)[0m malloc_consolidate(): invalid chunk size
E0816 10:32:17.435848080  508404 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0816 10:32:17.435902097  508404 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0816 10:32:17.435912643  508404 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 10:32:44,970 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:32:44,970 | fed_df.py:547 | Average fusion training loss : 0.007235878385603428, val accuracy : 0.7320399999999999, best val accuracy : 0.7394
INFO flwr 2023-08-16 10:32:44,972 | common.py:35 | Avg. local train loss : 4.659429259225726, train acc : 0.8249944444444444
INFO flwr 2023-08-16 10:32:47,468 | server.py:116 | fit progress: (27, 1.3176455627441406, {'server_test_acc': 0.7235}, 2277.6177618299844)
INFO flwr 2023-08-16 10:32:47,468 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-16 10:32:52,499 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=534298)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=534301)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:33:39,719 | server.py:229 | fit_round 28 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=534305)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:33:40,025 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=534301)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=534298)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=534305)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=534306)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=534308)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=534307)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=534309)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=534310)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=534309)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=534306)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=534310)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=534308)[0m malloc_consolidate(): invalid chunk size
E0816 10:33:41.034495169  508454 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=534307)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 10:34:08,829 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:34:08,830 | fed_df.py:547 | Average fusion training loss : 0.005640877562575042, val accuracy : 0.7230400000000001, best val accuracy : 0.7288
INFO flwr 2023-08-16 10:34:08,832 | common.py:35 | Avg. local train loss : 4.640302994847298, train acc : 0.8275027777777778
INFO flwr 2023-08-16 10:34:11,304 | server.py:116 | fit progress: (28, 1.3083310791015625, {'server_test_acc': 0.7266}, 2361.4536849819997)
INFO flwr 2023-08-16 10:34:11,304 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-16 10:34:16,326 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=607712)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:35:03,460 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-16 10:35:03,742 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=607712)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=607710)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=607713)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=607717)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=607716)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=607718)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=607715)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=607714)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=607713)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=607710)[0m malloc_consolidate(): invalid chunk size
E0816 10:35:04.389697885  654634 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=607716)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=607717)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=607714)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=607718)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=607715)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:35:32,597 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:35:32,597 | fed_df.py:547 | Average fusion training loss : 0.006436707682907581, val accuracy : 0.7316, best val accuracy : 0.7358
INFO flwr 2023-08-16 10:35:32,599 | common.py:35 | Avg. local train loss : 4.632451128214597, train acc : 0.8276999999999999
INFO flwr 2023-08-16 10:35:35,066 | server.py:116 | fit progress: (29, 1.3244483428955078, {'server_test_acc': 0.7273}, 2445.2156708539987)
INFO flwr 2023-08-16 10:35:35,066 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-16 10:35:40,254 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=681313)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:36:27,196 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-16 10:36:27,405 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-16 10:36:27,531 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=681311)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=681313)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=681315)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=681317)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=681316)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=681320)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=681318)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=681319)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=681311)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=681318)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=681315)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=681319)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=681317)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=681320)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=681316)[0m malloc_consolidate(): invalid chunk size
E0816 10:36:30.116961172  729264 chttp2_transport.cc:1079]             ipv4:145.136.62.38:57638: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 10:36:56,265 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:36:56,265 | fed_df.py:547 | Average fusion training loss : 0.011008784749545157, val accuracy : 0.7350800000000001, best val accuracy : 0.7452
INFO flwr 2023-08-16 10:36:56,267 | common.py:35 | Avg. local train loss : 4.637129860371352, train acc : 0.8263250000000001
INFO flwr 2023-08-16 10:36:58,758 | server.py:116 | fit progress: (30, 1.3641939208984375, {'server_test_acc': 0.7415}, 2528.907905330998)
INFO flwr 2023-08-16 10:36:58,758 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-16 10:36:58,758 | server.py:144 | FL finished in 2528.908273901994
INFO flwr 2023-08-16 10:36:58,759 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-16 10:36:58,760 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-16 10:36:58,760 | app.py:204 | app_fit: losses_centralized [(0, 2.319245477294922), (1, 1.5128369262695311), (2, 1.4916029907226562), (3, 1.4368529357910156), (4, 1.4065710388183594), (5, 1.225176318359375), (6, 1.259322348022461), (7, 1.2875899505615234), (8, 1.266434341430664), (9, 1.258098483276367), (10, 1.195894122314453), (11, 1.260543881225586), (12, 1.2577306549072265), (13, 1.2492872833251953), (14, 1.2559979431152344), (15, 1.2540185607910157), (16, 1.2806758972167969), (17, 1.2754174377441405), (18, 1.2570561920166015), (19, 1.282286929321289), (20, 1.2742237579345703), (21, 1.3130491119384766), (22, 1.3005873779296875), (23, 1.2872470245361327), (24, 1.262102471923828), (25, 1.3315126312255858), (26, 1.3402845153808594), (27, 1.3176455627441406), (28, 1.3083310791015625), (29, 1.3244483428955078), (30, 1.3641939208984375)]
INFO flwr 2023-08-16 10:36:58,760 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0811), (1, 0.4535), (2, 0.5344), (3, 0.5619), (4, 0.603), (5, 0.6436), (6, 0.6493), (7, 0.6553), (8, 0.6574), (9, 0.6686), (10, 0.6846), (11, 0.6942), (12, 0.6971), (13, 0.7008), (14, 0.6875), (15, 0.7108), (16, 0.7155), (17, 0.7099), (18, 0.7059), (19, 0.711), (20, 0.7142), (21, 0.7261), (22, 0.7209), (23, 0.7202), (24, 0.7261), (25, 0.7272), (26, 0.7251), (27, 0.7235), (28, 0.7266), (29, 0.7273), (30, 0.7415)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn38: task 0: Aborted
srun: Terminating StepId=3357205.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3357205
Cluster: snellius
User/Group: sunnys/sunnys
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 01:43:43
CPU Efficiency: 13.24% of 13:03:18 core-walltime
Job Wall-clock time: 00:43:31
Memory Utilized: 64.57 GB
Memory Efficiency: 53.81% of 120.00 GB
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
