-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:50000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:500
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:pathmnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:2.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:True
USE_KMEANS:True
USE_FEDPROX:True
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=50000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3430938/1692575296_362624587', seed=84, img_per_thread=2777)
will save 50000 patches in /scratch-local/sunnys.3430938/1692575296_362624587/single_img_crops/crops
50000 took 0.44min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-21 01:49:04,475 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-21 01:49:04,475 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3430938/1692575296_362624587/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3430938/1692575296_362624587/cifar-10-python.tar.gz to /scratch-local/sunnys.3430938/1692575296_362624587
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [342 114 363 765  49 204 467  25  55 116]
INFO flwr 2023-08-21 01:49:36,869 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-21 01:49:40,603	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-21 01:49:42,678 | app.py:179 | Flower VCE: Ray initialized with resources: {'memory': 103079215104.0, 'CPU': 18.0, 'object_store_memory': 61847529062.0, 'GPU': 1.0, 'accelerator_type:A100': 1.0, 'node:145.136.62.46': 1.0}
INFO flwr 2023-08-21 01:49:42,678 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-21 01:49:42,678 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-21 01:49:42,678 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-21 01:49:52,117 | server.py:91 | initial parameters (loss, other metrics): 2.319245477294922, {'server_test_acc': 0.0811}
INFO flwr 2023-08-21 01:49:52,117 | server.py:101 | FL starting
DEBUG flwr 2023-08-21 01:49:58,383 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 01:50:52,570 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-21 01:50:52,678 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-21 01:50:52,768 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3742535)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3742536)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3742540)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3742541)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3742539)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3742534)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3742537)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3742538)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3742534)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3742537)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3742536)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3742538)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3742539)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3742541)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3742540)[0m malloc_consolidate(): invalid chunk size
E0821 01:50:54.765657228 3838763 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=3742535)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 01:52:19,819 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 01:52:19,820 | fed_df.py:547 | Average fusion training loss : 0.013050240320153535, val accuracy : 0.32859999999999995, best val accuracy : 0.3508
INFO flwr 2023-08-21 01:52:19,821 | common.py:35 | Avg. local train loss : 7.238343196734785, train acc : 0.5433
INFO flwr 2023-08-21 01:52:22,380 | server.py:116 | fit progress: (1, 1.7553987030029297, {'server_test_acc': 0.3498}, 150.26206087402534)
INFO flwr 2023-08-21 01:52:22,380 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-21 01:52:28,483 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3993629)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 01:53:19,727 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-21 01:53:19,867 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3993629)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3993635)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3993628)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3993630)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3993633)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3993634)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3993631)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3993627)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3993631)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3993627)[0m double free or corruption (fasttop)
E0821 01:53:20.661260618 4097826 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=3993635)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3993628)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3993634)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3993633)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3993630)[0m malloc_consolidate(): invalid chunk size
E0821 01:53:35.205800673 4127224 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
E0821 01:54:45.767539919 4128208 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-21 01:54:53,747 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 01:54:53,748 | fed_df.py:547 | Average fusion training loss : 0.009939598103985191, val accuracy : 0.4678999999999999, best val accuracy : 0.5016
INFO flwr 2023-08-21 01:54:53,749 | common.py:35 | Avg. local train loss : 6.829935415461659, train acc : 0.5852305555555555
INFO flwr 2023-08-21 01:54:56,459 | server.py:116 | fit progress: (2, 1.43441650390625, {'server_test_acc': 0.5004}, 304.34179543703794)
INFO flwr 2023-08-21 01:54:56,460 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-21 01:55:02,628 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=80027)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 01:55:52,924 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-21 01:55:53,063 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=80027)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=80028)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=80029)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=80030)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=80034)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=80033)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=80031)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=80032)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=80029)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=80032)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=80030)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=80028)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=80034)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=80031)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=80033)[0m malloc_consolidate(): invalid chunk size
E0821 01:55:56.022346790  174567 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-08-21 01:57:27,336 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 01:57:27,336 | fed_df.py:547 | Average fusion training loss : 0.006657996699213981, val accuracy : 0.48656, best val accuracy : 0.5104
INFO flwr 2023-08-21 01:57:27,337 | common.py:35 | Avg. local train loss : 5.932163062691689, train acc : 0.6801583333333333
INFO flwr 2023-08-21 01:57:30,099 | server.py:116 | fit progress: (3, 1.441626806640625, {'server_test_acc': 0.5089}, 457.9815215310082)
INFO flwr 2023-08-21 01:57:30,099 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-21 01:57:36,289 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=331341)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=331340)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 01:58:27,464 | server.py:229 | fit_round 4 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=331342)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=331345)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 01:58:27,605 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=331339)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=331341)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=331342)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=331343)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=331345)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=331340)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=331337)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=331344)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=331339)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=331343)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=331344)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=331337)[0m malloc_consolidate(): invalid chunk size
E0821 01:58:29.848203867  424807 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-08-21 02:00:01,321 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:00:01,321 | fed_df.py:547 | Average fusion training loss : 0.006444591307546943, val accuracy : 0.5360400000000001, best val accuracy : 0.556
INFO flwr 2023-08-21 02:00:01,322 | common.py:35 | Avg. local train loss : 5.572923687100411, train acc : 0.7208444444444444
INFO flwr 2023-08-21 02:00:04,039 | server.py:116 | fit progress: (4, 1.3162313659667968, {'server_test_acc': 0.5487}, 611.9218883470166)
INFO flwr 2023-08-21 02:00:04,040 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-21 02:00:10,202 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=582273)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:01:00,223 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-21 02:01:00,331 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-21 02:01:00,420 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=582263)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=582273)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=582265)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=582266)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=582261)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=582260)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=582264)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=582262)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=582260)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=582265)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=582263)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=582266)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=582262)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=582264)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=582261)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 02:02:38,835 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:02:38,836 | fed_df.py:547 | Average fusion training loss : 0.006887396930251271, val accuracy : 0.62008, best val accuracy : 0.628
INFO flwr 2023-08-21 02:02:38,839 | common.py:35 | Avg. local train loss : 5.381692950800061, train acc : 0.7419055555555555
INFO flwr 2023-08-21 02:02:41,507 | server.py:116 | fit progress: (5, 1.1324166687011719, {'server_test_acc': 0.6268}, 769.3899710590485)
INFO flwr 2023-08-21 02:02:41,508 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-21 02:02:47,651 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=833827)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:03:37,191 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-21 02:03:37,330 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=833826)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=833827)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=833830)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=833825)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=833828)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=833831)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=833832)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=833829)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=833829)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=833826)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=833832)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=833825)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=833831)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=833830)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=833828)[0m malloc_consolidate(): invalid chunk size
E0821 02:03:39.358070020  426193 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-08-21 02:05:10,388 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:05:10,389 | fed_df.py:547 | Average fusion training loss : 0.004508475006558001, val accuracy : 0.5771, best val accuracy : 0.594
INFO flwr 2023-08-21 02:05:10,390 | common.py:35 | Avg. local train loss : 4.929222473129629, train acc : 0.7835027777777778
INFO flwr 2023-08-21 02:05:13,059 | server.py:116 | fit progress: (6, 1.2445139678955077, {'server_test_acc': 0.5864}, 920.9418180930661)
INFO flwr 2023-08-21 02:05:13,060 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-21 02:05:19,221 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1084551)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1084563)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1084555)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1084562)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1084557)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:06:11,700 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-21 02:06:11,838 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1084551)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1084555)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1084563)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1084562)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1084560)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1084559)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1084557)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1084556)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1084560)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1084559)[0m malloc_consolidate(): invalid chunk size
E0821 02:06:12.640290033 1177997 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=1084556)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 02:07:44,927 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:07:44,928 | fed_df.py:547 | Average fusion training loss : 0.004538608704460784, val accuracy : 0.52566, best val accuracy : 0.5534
INFO flwr 2023-08-21 02:07:44,929 | common.py:35 | Avg. local train loss : 4.670708580687642, train acc : 0.8078361111111111
INFO flwr 2023-08-21 02:07:47,638 | server.py:116 | fit progress: (7, 1.3297173156738282, {'server_test_acc': 0.5499}, 1075.5208393130451)
INFO flwr 2023-08-21 02:07:47,639 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-21 02:07:53,853 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1338023)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1338065)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:08:43,970 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-21 02:08:44,112 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1338023)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1338018)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1338112)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1338065)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1338113)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1338069)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1338110)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1338111)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1338113)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1338018)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1338110)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1338112)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1338069)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1338111)[0m malloc_consolidate(): invalid chunk size
E0821 02:08:47.013569713 1445880 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-08-21 02:10:18,047 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:10:18,047 | fed_df.py:547 | Average fusion training loss : 0.0037457601570058613, val accuracy : 0.64314, best val accuracy : 0.6506
INFO flwr 2023-08-21 02:10:18,048 | common.py:35 | Avg. local train loss : 4.961251606792213, train acc : 0.7845277777777777
INFO flwr 2023-08-21 02:10:20,739 | server.py:116 | fit progress: (8, 1.116204315185547, {'server_test_acc': 0.6409}, 1228.6216761759715)
INFO flwr 2023-08-21 02:10:20,739 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-21 02:10:26,984 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1615020)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:11:17,938 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-21 02:11:18,079 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1615022)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1615026)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1615023)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1615025)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1615021)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1615019)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1615024)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1615020)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1615026)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1615022)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1615021)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1615024)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1615023)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1615019)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1615025)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:12:51,183 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:12:51,183 | fed_df.py:547 | Average fusion training loss : 0.003163679180201143, val accuracy : 0.6527, best val accuracy : 0.666
INFO flwr 2023-08-21 02:12:51,184 | common.py:35 | Avg. local train loss : 4.881776842474937, train acc : 0.7926722222222222
INFO flwr 2023-08-21 02:12:53,861 | server.py:116 | fit progress: (9, 1.0721879821777345, {'server_test_acc': 0.6598}, 1381.7433554939926)
INFO flwr 2023-08-21 02:12:53,861 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-21 02:13:00,152 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1865676)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:13:51,314 | server.py:229 | fit_round 10 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1865675)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1865673)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:13:51,425 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-21 02:13:51,514 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1865674)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1865671)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1865670)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1865673)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1865675)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1865672)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1865676)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1865677)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1865674)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1865670)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1865671)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1865677)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1865672)[0m malloc_consolidate(): invalid chunk size
E0821 02:13:53.894775942 1959675 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
INFO flwr 2023-08-21 02:15:24,513 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:15:24,513 | fed_df.py:547 | Average fusion training loss : 0.0060818582798819985, val accuracy : 0.60972, best val accuracy : 0.6258
INFO flwr 2023-08-21 02:15:24,514 | common.py:35 | Avg. local train loss : 4.689713321626187, train acc : 0.8144472222222222
INFO flwr 2023-08-21 02:15:27,230 | server.py:116 | fit progress: (10, 1.1759457611083985, {'server_test_acc': 0.6173}, 1535.1125923050568)
INFO flwr 2023-08-21 02:15:27,230 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-21 02:15:33,361 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2116807)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2116805)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2116808)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:16:24,511 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-21 02:16:24,651 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2116801)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2116807)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2116805)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2116804)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2116803)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2116808)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2116802)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2116806)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2116804)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2116803)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2116801)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2116806)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2116802)[0m malloc_consolidate(): invalid chunk size
E0821 02:16:27.246677341 1960413 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
INFO flwr 2023-08-21 02:17:58,168 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:17:58,168 | fed_df.py:547 | Average fusion training loss : 0.0023517910880036653, val accuracy : 0.6604800000000001, best val accuracy : 0.681
INFO flwr 2023-08-21 02:17:58,169 | common.py:35 | Avg. local train loss : 4.720030132308602, train acc : 0.8079027777777779
INFO flwr 2023-08-21 02:18:00,905 | server.py:116 | fit progress: (11, 1.066291845703125, {'server_test_acc': 0.6723}, 1688.7873172030086)
INFO flwr 2023-08-21 02:18:00,905 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-21 02:18:07,070 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2367429)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2367435)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2367437)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:18:57,423 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-21 02:18:57,563 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2367429)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2367435)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2367433)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2367438)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2367437)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2367434)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2367439)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2367436)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2367434)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2367436)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2367433)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2367439)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2367438)[0m malloc_consolidate(): invalid chunk size
E0821 02:19:00.233606788 2460146 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
INFO flwr 2023-08-21 02:20:31,216 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:20:31,216 | fed_df.py:547 | Average fusion training loss : 0.002258380493381992, val accuracy : 0.69244, best val accuracy : 0.7006
INFO flwr 2023-08-21 02:20:31,218 | common.py:35 | Avg. local train loss : 4.937554188072681, train acc : 0.790875
INFO flwr 2023-08-21 02:20:33,900 | server.py:116 | fit progress: (12, 0.973506820678711, {'server_test_acc': 0.6959}, 1841.7827244540676)
INFO flwr 2023-08-21 02:20:33,900 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-21 02:20:40,080 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2618601)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2618596)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2618617)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:21:30,053 | server.py:229 | fit_round 13 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2618595)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2618616)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 02:21:30,196 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2618596)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2618595)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2618601)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2618616)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2618618)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2618617)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2618620)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2618619)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2618620)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2618618)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2618619)[0m malloc_consolidate(): invalid chunk size
E0821 02:21:32.664133229 2461436 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-21 02:23:03,205 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:23:03,206 | fed_df.py:547 | Average fusion training loss : 0.0020581823126412926, val accuracy : 0.6715000000000001, best val accuracy : 0.6862
INFO flwr 2023-08-21 02:23:03,207 | common.py:35 | Avg. local train loss : 4.589713713526725, train acc : 0.8223027777777777
INFO flwr 2023-08-21 02:23:05,883 | server.py:116 | fit progress: (13, 1.0283838653564452, {'server_test_acc': 0.6771}, 1993.7658833990572)
INFO flwr 2023-08-21 02:23:05,884 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-21 02:23:12,021 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2867374)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2867514)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:24:01,117 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-21 02:24:01,257 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2867374)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2867445)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2867514)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2867444)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2867515)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2867513)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2867516)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2867517)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2867445)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2867515)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2867517)[0m malloc_consolidate(): invalid chunk size
E0821 02:24:02.841529842 2710084 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=2867516)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2867513)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2867444)[0m malloc_consolidate(): invalid chunk size
E0821 02:24:54.468194774 3065064 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
INFO flwr 2023-08-21 02:25:35,427 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:25:35,428 | fed_df.py:547 | Average fusion training loss : 0.0020187588722910734, val accuracy : 0.6410199999999999, best val accuracy : 0.654
INFO flwr 2023-08-21 02:25:35,429 | common.py:35 | Avg. local train loss : 4.424249583482743, train acc : 0.8387861111111111
INFO flwr 2023-08-21 02:25:38,132 | server.py:116 | fit progress: (14, 1.1067619873046874, {'server_test_acc': 0.6434}, 2146.0147906040074)
INFO flwr 2023-08-21 02:25:38,133 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-21 02:25:44,281 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3147448)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:26:33,905 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-21 02:26:34,015 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-21 02:26:34,104 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3147448)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3147451)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3147452)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3147454)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3147455)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3147453)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3147456)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3147450)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3147450)[0m 
[2m[36m(launch_and_fit pid=3147451)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3147456)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3147454)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3147450)[0m malloc_consolidate(): invalid chunk size
E0821 02:26:35.255332389 3234062 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=3147452)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3147455)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3147453)[0m double free or corruption (fasttop)
E0821 02:28:00.307958738 3234552 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:28:07,449 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:28:07,449 | fed_df.py:547 | Average fusion training loss : 0.006418900826945901, val accuracy : 0.68996, best val accuracy : 0.6992
INFO flwr 2023-08-21 02:28:07,450 | common.py:35 | Avg. local train loss : 4.521766689419746, train acc : 0.8321638888888889
INFO flwr 2023-08-21 02:28:10,145 | server.py:116 | fit progress: (15, 1.0319205810546874, {'server_test_acc': 0.691}, 2298.027343327063)
INFO flwr 2023-08-21 02:28:10,145 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-21 02:28:16,288 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3398150)[0m corrupted size vs. prev_size in fastbins
DEBUG flwr 2023-08-21 02:29:05,653 | server.py:229 | fit_round 16 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3398124)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3398162)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:29:05,797 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3398127)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3398124)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3398149)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3398126)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3398150)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3398162)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3398161)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3398160)[0m Fitting Client 14
E0821 02:29:06.293828576 3481356 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3398161)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3398149)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3398160)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3398126)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3398127)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:30:39,419 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:30:39,420 | fed_df.py:547 | Average fusion training loss : 0.0012969226272543893, val accuracy : 0.69966, best val accuracy : 0.709
INFO flwr 2023-08-21 02:30:39,421 | common.py:35 | Avg. local train loss : 4.339680866152048, train acc : 0.8458722222222222
INFO flwr 2023-08-21 02:30:42,125 | server.py:116 | fit progress: (16, 1.0261047912597656, {'server_test_acc': 0.7004}, 2450.0074382959865)
INFO flwr 2023-08-21 02:30:42,125 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-21 02:30:48,322 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3643676)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:31:36,314 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-21 02:31:36,471 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3643603)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3643604)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3643606)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3643605)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3643607)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3643676)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3643675)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3643677)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3643605)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3643607)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3643606)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3643675)[0m malloc_consolidate(): invalid chunk size
E0821 02:31:37.650228102 3725892 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3643604)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3643677)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3643603)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:33:10,061 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:33:10,062 | fed_df.py:547 | Average fusion training loss : 0.0012150881759589538, val accuracy : 0.6717599999999999, best val accuracy : 0.684
INFO flwr 2023-08-21 02:33:10,063 | common.py:35 | Avg. local train loss : 4.46371258981526, train acc : 0.837888888888889
INFO flwr 2023-08-21 02:33:12,771 | server.py:116 | fit progress: (17, 1.0894239990234376, {'server_test_acc': 0.6762}, 2600.653726549004)
INFO flwr 2023-08-21 02:33:12,771 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-21 02:33:19,018 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 02:34:06,823 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-21 02:34:06,967 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3895424)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3895424)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3895355)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3895353)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3895354)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3895426)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3895425)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3895356)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3895352)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3895354)[0m malloc_consolidate(): invalid chunk size
E0821 02:34:07.446851039 3726291 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3895353)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3895352)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3895426)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3895356)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3895355)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3895425)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:35:41,210 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:35:41,210 | fed_df.py:547 | Average fusion training loss : 0.001584700193023309, val accuracy : 0.7135800000000001, best val accuracy : 0.7214
INFO flwr 2023-08-21 02:35:41,212 | common.py:35 | Avg. local train loss : 4.558451710641384, train acc : 0.82915
INFO flwr 2023-08-21 02:35:43,928 | server.py:116 | fit progress: (18, 0.9844465454101563, {'server_test_acc': 0.7156}, 2751.8109854829963)
INFO flwr 2023-08-21 02:35:43,929 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-21 02:35:50,047 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 02:36:37,846 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-21 02:36:37,986 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4141063)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4141065)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4140994)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4141066)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4141101)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4141135)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4141136)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4141137)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4141101)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4140994)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4141065)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4141063)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4141135)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=4141137)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4141136)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4141066)[0m double free or corruption (fasttop)
E0821 02:36:40.866207487   26870 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:38:13,306 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:38:13,306 | fed_df.py:547 | Average fusion training loss : 0.0018563562610652297, val accuracy : 0.6777599999999999, best val accuracy : 0.692
INFO flwr 2023-08-21 02:38:13,307 | common.py:35 | Avg. local train loss : 4.375066739320755, train acc : 0.8479277777777777
INFO flwr 2023-08-21 02:38:16,000 | server.py:116 | fit progress: (19, 1.0659181518554688, {'server_test_acc': 0.6867}, 2903.8825162029825)
INFO flwr 2023-08-21 02:38:16,000 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-21 02:38:22,169 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 02:39:10,927 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-21 02:39:11,037 | fed_df.py:365 | Warm start at round 20
[2m[36m(launch_and_fit pid=198643)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 02:39:11,128 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=198573)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=198642)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=198644)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=198643)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=198574)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=198572)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=198646)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=198645)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=198644)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=198573)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=198572)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=198645)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=198574)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=198642)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=198646)[0m malloc_consolidate(): invalid chunk size
E0821 02:39:15.946321770  296175 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:40:46,938 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:40:46,938 | fed_df.py:547 | Average fusion training loss : 0.006041410319856368, val accuracy : 0.71898, best val accuracy : 0.7254
INFO flwr 2023-08-21 02:40:46,939 | common.py:35 | Avg. local train loss : 4.4854398380965, train acc : 0.8367722222222223
INFO flwr 2023-08-21 02:40:49,659 | server.py:116 | fit progress: (20, 1.0549832733154296, {'server_test_acc': 0.7194}, 3057.5416125400225)
INFO flwr 2023-08-21 02:40:49,659 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-21 02:40:55,882 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=478252)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:41:43,520 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-21 02:41:43,678 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=478320)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=478252)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=478251)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=478180)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=478320)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=478323)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=478249)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=478321)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=478322)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=478180)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=478251)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=478249)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=478321)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=478323)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=478322)[0m malloc_consolidate(): invalid chunk size
E0821 02:41:48.093310259  297859 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:43:17,934 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:43:17,934 | fed_df.py:547 | Average fusion training loss : 0.0009434002958005294, val accuracy : 0.72058, best val accuracy : 0.7314
INFO flwr 2023-08-21 02:43:17,935 | common.py:35 | Avg. local train loss : 4.4635637402534485, train acc : 0.8369916666666667
INFO flwr 2023-08-21 02:43:20,631 | server.py:116 | fit progress: (21, 1.0701917938232421, {'server_test_acc': 0.7261}, 3208.5132337140385)
INFO flwr 2023-08-21 02:43:20,631 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-21 02:43:26,872 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=728005)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=728004)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:44:14,936 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-21 02:44:15,077 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=728005)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=728008)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=728006)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=728004)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=728077)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=728079)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=728076)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=728078)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=728077)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=728078)[0m double free or corruption (fasttop)
E0821 02:44:15.634665796  562250 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=728079)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=728006)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=728076)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=728008)[0m double free or corruption (fasttop)
E0821 02:45:17.383691627  914002 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:45:49,979 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:45:49,979 | fed_df.py:547 | Average fusion training loss : 0.0010002749211271294, val accuracy : 0.71594, best val accuracy : 0.7194
INFO flwr 2023-08-21 02:45:49,981 | common.py:35 | Avg. local train loss : 4.527726918458939, train acc : 0.8360055555555557
INFO flwr 2023-08-21 02:45:52,682 | server.py:116 | fit progress: (22, 1.0677423828125, {'server_test_acc': 0.7195}, 3360.5648597769905)
INFO flwr 2023-08-21 02:45:52,683 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-21 02:45:58,918 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 02:46:46,697 | server.py:229 | fit_round 23 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=978765)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:46:46,840 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=978766)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=978765)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=978764)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=978767)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=978694)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=978748)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=978768)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=978763)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=978767)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=978764)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=978748)[0m double free or corruption (fasttop)
E0821 02:46:47.656158812  916292 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=978768)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=978763)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=978694)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=978766)[0m malloc_consolidate(): invalid chunk size
E0821 02:47:06.843664712 1093551 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:48:22,011 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:48:22,012 | fed_df.py:547 | Average fusion training loss : 0.0012797163303475826, val accuracy : 0.6933199999999999, best val accuracy : 0.7046
INFO flwr 2023-08-21 02:48:22,013 | common.py:35 | Avg. local train loss : 4.36393776461482, train acc : 0.8515027777777776
INFO flwr 2023-08-21 02:48:24,716 | server.py:116 | fit progress: (23, 1.0558833923339843, {'server_test_acc': 0.6942}, 3512.598479978973)
INFO flwr 2023-08-21 02:48:24,716 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-21 02:48:30,982 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1229621)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:49:18,899 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-21 02:49:19,056 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1229623)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1229623)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1229619)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1229622)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1229617)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1229618)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1229615)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1229621)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1229620)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1229615)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1229620)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1229619)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1229622)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1229617)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1229618)[0m corrupted size vs. prev_size in fastbins
E0821 02:49:23.459725364 1309146 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:50:54,086 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:50:54,086 | fed_df.py:547 | Average fusion training loss : 0.0011694711610907688, val accuracy : 0.70884, best val accuracy : 0.722
INFO flwr 2023-08-21 02:50:54,088 | common.py:35 | Avg. local train loss : 4.305941745266318, train acc : 0.8558138888888889
INFO flwr 2023-08-21 02:50:56,840 | server.py:116 | fit progress: (24, 1.0018981689453126, {'server_test_acc': 0.7174}, 3664.7223717540037)
INFO flwr 2023-08-21 02:50:56,840 | server.py:163 | evaluate_round 24: no clients selected, cancel
E0821 02:50:58.229573857 1473602 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
DEBUG flwr 2023-08-21 02:51:03,063 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1480183)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1480186)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1480181)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:51:50,593 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-21 02:51:50,703 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-21 02:51:50,792 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1480182)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1480180)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1480183)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1480185)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1480187)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1480186)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1480184)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1480181)[0m Fitting Client 8
E0821 02:51:51.411230891 1476121 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1480180)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1480184)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1480182)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1480187)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1480185)[0m malloc_consolidate(): invalid chunk size
E0821 02:53:08.507807231 1554219 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:53:24,823 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:53:24,823 | fed_df.py:547 | Average fusion training loss : 0.0054922304375795645, val accuracy : 0.7222799999999999, best val accuracy : 0.73
INFO flwr 2023-08-21 02:53:24,825 | common.py:35 | Avg. local train loss : 4.541140549257397, train acc : 0.8337749999999999
INFO flwr 2023-08-21 02:53:27,640 | server.py:116 | fit progress: (25, 1.1231207641601562, {'server_test_acc': 0.722}, 3815.5227077730233)
INFO flwr 2023-08-21 02:53:27,640 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-21 02:53:33,834 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1729546)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:54:22,204 | server.py:229 | fit_round 26 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1729615)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 02:54:22,347 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1729618)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1729617)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1729545)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1729546)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1729547)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1729615)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1729619)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1729616)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1729616)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1729617)[0m malloc_consolidate(): invalid chunk size
E0821 02:54:22.696017345 1692555 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1729547)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1729545)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1729619)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1729618)[0m malloc_consolidate(): invalid chunk size
E0821 02:55:03.387401609 1902976 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:55:57,461 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:55:57,462 | fed_df.py:547 | Average fusion training loss : 0.0008148603357840329, val accuracy : 0.7081199999999999, best val accuracy : 0.7218
INFO flwr 2023-08-21 02:55:57,463 | common.py:35 | Avg. local train loss : 4.235076969489455, train acc : 0.8595611111111111
INFO flwr 2023-08-21 02:56:00,213 | server.py:116 | fit progress: (26, 1.194866162109375, {'server_test_acc': 0.7181}, 3968.0950623890385)
INFO flwr 2023-08-21 02:56:00,213 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-21 02:56:06,436 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2008207)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:56:54,198 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-21 02:56:54,340 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2008207)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2008209)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2008215)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2008213)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2008212)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2008210)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2008214)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2008211)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2008210)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2008213)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2008214)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2008209)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2008211)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2008212)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2008215)[0m malloc_consolidate(): invalid chunk size
E0821 02:57:08.578300510 2080908 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 02:58:04.131202962 2108650 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:58:29,354 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:58:29,354 | fed_df.py:547 | Average fusion training loss : 0.0007892295259516686, val accuracy : 0.7280599999999999, best val accuracy : 0.7426
INFO flwr 2023-08-21 02:58:29,355 | common.py:35 | Avg. local train loss : 4.513563802093268, train acc : 0.8394
INFO flwr 2023-08-21 02:58:32,054 | server.py:116 | fit progress: (27, 1.053533270263672, {'server_test_acc': 0.73}, 4119.936332943034)
INFO flwr 2023-08-21 02:58:32,054 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-21 02:58:38,275 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2257413)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:59:26,172 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-21 02:59:26,314 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2257413)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2257412)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2257484)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2257483)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2257482)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2257411)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2257343)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2257485)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2257483)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2257482)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2257411)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2257485)[0m malloc_consolidate(): invalid chunk size
E0821 02:59:27.424912375 2206530 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2257343)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2257484)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2257412)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 03:01:01,841 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 03:01:01,842 | fed_df.py:547 | Average fusion training loss : 0.0008099810989806429, val accuracy : 0.72868, best val accuracy : 0.7362
INFO flwr 2023-08-21 03:01:01,843 | common.py:35 | Avg. local train loss : 4.363426838070154, train acc : 0.8530666666666666
INFO flwr 2023-08-21 03:01:04,549 | server.py:116 | fit progress: (28, 1.0321738342285156, {'server_test_acc': 0.7328}, 4272.43120857398)
INFO flwr 2023-08-21 03:01:04,549 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-21 03:01:10,748 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2507399)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 03:01:58,794 | server.py:229 | fit_round 29 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2507317)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 03:01:58,940 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2507317)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2507399)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2507434)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2507397)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2507459)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2507400)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2507402)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2507398)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2507400)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2507434)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2507402)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2507397)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2507398)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2507459)[0m malloc_consolidate(): invalid chunk size
E0821 03:02:47.780436476 2329683 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 03:03:34,382 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 03:03:34,382 | fed_df.py:547 | Average fusion training loss : 0.0009504458094597794, val accuracy : 0.7272200000000001, best val accuracy : 0.7376
INFO flwr 2023-08-21 03:03:34,384 | common.py:35 | Avg. local train loss : 4.414053972437978, train acc : 0.8475250000000001
INFO flwr 2023-08-21 03:03:37,105 | server.py:116 | fit progress: (29, 1.008482260131836, {'server_test_acc': 0.7307}, 4424.987879139022)
INFO flwr 2023-08-21 03:03:37,106 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-21 03:03:43,296 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 03:04:31,032 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-21 03:04:31,143 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-21 03:04:31,231 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2757240)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2757241)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2757238)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2757242)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2757243)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2757239)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2757244)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2757236)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2757240)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2757239)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2757236)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2757241)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2757238)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2757243)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2757244)[0m malloc_consolidate(): invalid chunk size
E0821 03:04:33.520205532 2671550 chttp2_transport.cc:1079]             ipv4:145.136.62.46:44002: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2757242)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 03:06:07,414 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 03:06:07,414 | fed_df.py:547 | Average fusion training loss : 0.004965825931052678, val accuracy : 0.67682, best val accuracy : 0.699
INFO flwr 2023-08-21 03:06:07,415 | common.py:35 | Avg. local train loss : 4.375049619376659, train acc : 0.8512027777777778
INFO flwr 2023-08-21 03:06:10,173 | server.py:116 | fit progress: (30, 1.2584784057617187, {'server_test_acc': 0.6971}, 4578.055057169055)
INFO flwr 2023-08-21 03:06:10,173 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-21 03:06:10,173 | server.py:144 | FL finished in 4578.055424893042
INFO flwr 2023-08-21 03:06:10,173 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-21 03:06:10,174 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-21 03:06:10,174 | app.py:204 | app_fit: losses_centralized [(0, 2.319245477294922), (1, 1.7553987030029297), (2, 1.43441650390625), (3, 1.441626806640625), (4, 1.3162313659667968), (5, 1.1324166687011719), (6, 1.2445139678955077), (7, 1.3297173156738282), (8, 1.116204315185547), (9, 1.0721879821777345), (10, 1.1759457611083985), (11, 1.066291845703125), (12, 0.973506820678711), (13, 1.0283838653564452), (14, 1.1067619873046874), (15, 1.0319205810546874), (16, 1.0261047912597656), (17, 1.0894239990234376), (18, 0.9844465454101563), (19, 1.0659181518554688), (20, 1.0549832733154296), (21, 1.0701917938232421), (22, 1.0677423828125), (23, 1.0558833923339843), (24, 1.0018981689453126), (25, 1.1231207641601562), (26, 1.194866162109375), (27, 1.053533270263672), (28, 1.0321738342285156), (29, 1.008482260131836), (30, 1.2584784057617187)]
INFO flwr 2023-08-21 03:06:10,174 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0811), (1, 0.3498), (2, 0.5004), (3, 0.5089), (4, 0.5487), (5, 0.6268), (6, 0.5864), (7, 0.5499), (8, 0.6409), (9, 0.6598), (10, 0.6173), (11, 0.6723), (12, 0.6959), (13, 0.6771), (14, 0.6434), (15, 0.691), (16, 0.7004), (17, 0.6762), (18, 0.7156), (19, 0.6867), (20, 0.7194), (21, 0.7261), (22, 0.7195), (23, 0.6942), (24, 0.7174), (25, 0.722), (26, 0.7181), (27, 0.73), (28, 0.7328), (29, 0.7307), (30, 0.6971)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn46: task 0: Aborted
srun: Terminating StepId=3430938.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3430938
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 02:59:38
CPU Efficiency: 12.40% of 1-00:08:24 core-walltime
Job Wall-clock time: 01:20:28
Memory Utilized: 52.34 GB
Memory Efficiency: 43.62% of 120.00 GB
