-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:50000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:10
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:organamnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:True
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=50000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3425001/1692485638_232261787', seed=84, img_per_thread=2777)
will save 50000 patches in /scratch-local/sunnys.3425001/1692485638_232261787/single_img_crops/crops
50000 took 0.39min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-20 00:54:36,701 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-20 00:54:36,701 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3425001/1692485638_232261787/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3425001/1692485638_232261787/cifar-10-python.tar.gz to /scratch-local/sunnys.3425001/1692485638_232261787
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [342 114 363 765  49 204 467  25  55 116]
INFO flwr 2023-08-20 00:55:00,994 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-20 00:55:03,752	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-20 00:55:04,711 | app.py:179 | Flower VCE: Ray initialized with resources: {'GPU': 1.0, 'object_store_memory': 61847529062.0, 'CPU': 18.0, 'memory': 103079215104.0, 'node:145.136.62.22': 1.0, 'accelerator_type:A100': 1.0}
INFO flwr 2023-08-20 00:55:04,711 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-20 00:55:04,711 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-20 00:55:04,711 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-20 00:55:15,703 | server.py:91 | initial parameters (loss, other metrics): 2.319245477294922, {'server_test_acc': 0.0811}
INFO flwr 2023-08-20 00:55:15,703 | server.py:101 | FL starting
DEBUG flwr 2023-08-20 00:55:21,752 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3100637)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 00:55:55,926 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-20 00:55:56,036 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-20 00:55:56,125 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3100641)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3100639)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3100637)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3100636)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3100638)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3100642)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3100635)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3100640)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3100636)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3100640)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3100639)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3100638)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3100642)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3100635)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3100641)[0m malloc_consolidate(): invalid chunk size
E0820 00:55:58.462852934 3127384 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 00:55:58.463066946 3127384 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 00:55:58.463085318 3127384 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 00:55:58.463098240 3127384 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 00:55:58.463110227 3127384 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 00:55:58.463121935 3127384 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 00:55:58.463132852 3127384 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-08-20 00:56:40,015 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:56:40,015 | fed_df.py:547 | Average fusion training loss : 0.03549340064823627, val accuracy : 0.30355999999999994, best val accuracy : 0.315
INFO flwr 2023-08-20 00:56:40,016 | common.py:35 | Avg. local train loss : 8.281458170711995, train acc : 0.4380277777777778
INFO flwr 2023-08-20 00:56:42,563 | server.py:116 | fit progress: (1, 1.9777800048828125, {'server_test_acc': 0.3132}, 86.85973506700248)
INFO flwr 2023-08-20 00:56:42,563 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-20 00:56:48,385 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 00:57:19,963 | server.py:229 | fit_round 2 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3167366)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:57:20,109 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3167363)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3167366)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3167369)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3167367)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3167364)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3167365)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3167368)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3167370)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3167364)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3167363)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3167368)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3167370)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3167365)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3167369)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3167367)[0m double free or corruption (fasttop)
E0820 00:57:23.068845556 3127586 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
INFO flwr 2023-08-20 00:58:06,773 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:58:06,774 | fed_df.py:547 | Average fusion training loss : 0.027605489064007997, val accuracy : 0.32212, best val accuracy : 0.3554
INFO flwr 2023-08-20 00:58:06,774 | common.py:35 | Avg. local train loss : 7.272024820744991, train acc : 0.5363666666666667
INFO flwr 2023-08-20 00:58:09,431 | server.py:116 | fit progress: (2, 1.9165531799316406, {'server_test_acc': 0.3564}, 173.72788869822398)
INFO flwr 2023-08-20 00:58:09,431 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-20 00:58:15,340 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3234513)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 00:58:47,368 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-20 00:58:47,514 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3234517)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3234513)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3234512)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3234519)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3234514)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3234518)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3234515)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3234516)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3234518)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3234519)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3234514)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3234515)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3234516)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3234512)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3234517)[0m malloc_consolidate(): invalid chunk size
E0820 00:58:50.939776742 3195041 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-08-20 00:59:34,135 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:59:34,135 | fed_df.py:547 | Average fusion training loss : 0.014101717377081513, val accuracy : 0.44488000000000005, best val accuracy : 0.4648
INFO flwr 2023-08-20 00:59:34,136 | common.py:35 | Avg. local train loss : 6.866258318722249, train acc : 0.581261111111111
INFO flwr 2023-08-20 00:59:36,785 | server.py:116 | fit progress: (3, 1.5061278533935547, {'server_test_acc': 0.4555}, 261.0818249681033)
INFO flwr 2023-08-20 00:59:36,785 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-20 00:59:42,668 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 01:00:14,190 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-20 01:00:14,334 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3301331)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3301332)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3301333)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3301330)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3301336)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3301329)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3301335)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3301334)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3301335)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3301336)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3301334)[0m malloc_consolidate(): invalid chunk size
E0820 01:00:15.274983856 3262202 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
E0820 01:00:15.275109851 3262202 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
[2m[36m(launch_and_fit pid=3301331)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3301332)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3301330)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3301333)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3301329)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 01:01:01,211 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:01:01,211 | fed_df.py:547 | Average fusion training loss : 0.008899133138358594, val accuracy : 0.49212000000000006, best val accuracy : 0.5062
INFO flwr 2023-08-20 01:01:01,212 | common.py:35 | Avg. local train loss : 6.48072202578187, train acc : 0.6269
INFO flwr 2023-08-20 01:01:03,866 | server.py:116 | fit progress: (4, 1.3947014099121093, {'server_test_acc': 0.5044}, 348.16315269703045)
INFO flwr 2023-08-20 01:01:03,867 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-20 01:01:09,786 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3368540)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 01:01:41,958 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-20 01:01:42,070 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-20 01:01:42,160 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3368540)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3368543)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3368538)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3368542)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3368539)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3368541)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3368544)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3368545)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3368539)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3368544)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3368541)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3368538)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3368545)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3368542)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3368543)[0m malloc_consolidate(): invalid chunk size
E0820 01:01:44.636499048 3394973 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-08-20 01:02:28,804 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:02:28,804 | fed_df.py:547 | Average fusion training loss : 0.014900597307831049, val accuracy : 0.45228, best val accuracy : 0.4682
INFO flwr 2023-08-20 01:02:28,805 | common.py:35 | Avg. local train loss : 6.114100653678179, train acc : 0.6599555555555555
INFO flwr 2023-08-20 01:02:31,438 | server.py:116 | fit progress: (5, 1.6327973175048829, {'server_test_acc': 0.4665}, 435.73488266486675)
INFO flwr 2023-08-20 01:02:31,438 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-20 01:02:37,327 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3435070)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 01:03:08,830 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-20 01:03:08,974 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3435070)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3435073)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3435072)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3435075)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3435076)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3435071)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3435077)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3435074)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3435076)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3435077)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3435072)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3435071)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3435074)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3435075)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3435073)[0m malloc_consolidate(): invalid chunk size
E0820 01:03:12.446790396 3462153 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-08-20 01:03:55,767 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:03:55,767 | fed_df.py:547 | Average fusion training loss : 0.02675117229670286, val accuracy : 0.47675999999999996, best val accuracy : 0.4832
INFO flwr 2023-08-20 01:03:55,768 | common.py:35 | Avg. local train loss : 5.561107830703259, train acc : 0.7142944444444445
INFO flwr 2023-08-20 01:03:58,466 | server.py:116 | fit progress: (6, 1.55310673828125, {'server_test_acc': 0.4845}, 522.7623760038987)
INFO flwr 2023-08-20 01:03:58,466 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-20 01:04:04,369 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3502205)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 01:04:36,406 | server.py:229 | fit_round 7 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3502223)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 01:04:36,554 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3502207)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3502222)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3502223)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3502224)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3502204)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3502205)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3502221)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3502206)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3502222)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3502206)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3502207)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3502221)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3502224)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3502204)[0m malloc_consolidate(): invalid chunk size
E0820 01:04:40.183715394 3463201 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-08-20 01:05:23,658 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:05:23,658 | fed_df.py:547 | Average fusion training loss : 0.01648087179660797, val accuracy : 0.5012800000000001, best val accuracy : 0.5186
INFO flwr 2023-08-20 01:05:23,660 | common.py:35 | Avg. local train loss : 6.042945760488511, train acc : 0.6723833333333333
INFO flwr 2023-08-20 01:05:26,334 | server.py:116 | fit progress: (7, 1.4775602783203126, {'server_test_acc': 0.5182}, 610.6308974861167)
INFO flwr 2023-08-20 01:05:26,334 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-20 01:05:32,413 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3568984)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3568986)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 01:06:04,140 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-20 01:06:04,284 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3568984)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3568986)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3568989)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3568992)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3568991)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3568987)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3568990)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3568988)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3568990)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3568987)[0m malloc_consolidate(): invalid chunk size
E0820 01:06:05.186227844 3530233 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=3568992)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3568989)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3568991)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3568988)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 01:06:50,752 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:06:50,753 | fed_df.py:547 | Average fusion training loss : 0.012164862437173725, val accuracy : 0.55216, best val accuracy : 0.568
INFO flwr 2023-08-20 01:06:50,754 | common.py:35 | Avg. local train loss : 5.935499636083841, train acc : 0.6779888888888889
INFO flwr 2023-08-20 01:06:53,440 | server.py:116 | fit progress: (8, 1.300870004272461, {'server_test_acc': 0.566}, 697.7372088851407)
INFO flwr 2023-08-20 01:06:53,441 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-20 01:06:59,426 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3637234)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 01:07:31,235 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-20 01:07:31,381 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3637143)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3637197)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3637206)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3637233)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3637234)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3637204)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3637158)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3637199)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3637233)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3637204)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3637158)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3637143)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3637206)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3637199)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3637197)[0m malloc_consolidate(): invalid chunk size
E0820 01:07:33.607546146 3595223 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-08-20 01:08:18,287 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:08:18,288 | fed_df.py:547 | Average fusion training loss : 0.012067246224731206, val accuracy : 0.54796, best val accuracy : 0.5636
INFO flwr 2023-08-20 01:08:18,289 | common.py:35 | Avg. local train loss : 5.7006277307868, train acc : 0.7089888888888889
INFO flwr 2023-08-20 01:08:20,958 | server.py:116 | fit progress: (9, 1.3594434020996093, {'server_test_acc': 0.5636}, 785.2548773512244)
INFO flwr 2023-08-20 01:08:20,958 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-20 01:08:26,906 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 01:08:58,507 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-20 01:08:58,622 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-20 01:08:58,710 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3731751)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3731756)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3731752)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3731757)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3731754)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3731755)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3731750)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3731758)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3731751)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3731758)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3731757)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3731752)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3731755)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3731754)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3731756)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3731750)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 01:09:45,478 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:09:45,478 | fed_df.py:547 | Average fusion training loss : 0.01217712551355362, val accuracy : 0.61172, best val accuracy : 0.6212
INFO flwr 2023-08-20 01:09:45,479 | common.py:35 | Avg. local train loss : 5.810163895040751, train acc : 0.6934944444444445
INFO flwr 2023-08-20 01:09:48,155 | server.py:116 | fit progress: (10, 1.1737774047851564, {'server_test_acc': 0.6064}, 872.4519765069708)
INFO flwr 2023-08-20 01:09:48,155 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-20 01:09:54,099 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3798562)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3798558)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 01:10:25,232 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-20 01:10:25,377 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3798558)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3798562)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3798563)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3798568)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3798564)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3798567)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3798566)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3798565)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3798566)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3798565)[0m double free or corruption (fasttop)
E0820 01:10:26.523432848 3824488 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=3798564)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3798568)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3798567)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3798563)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 01:11:12,426 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:11:12,426 | fed_df.py:547 | Average fusion training loss : 0.011630341017618775, val accuracy : 0.61336, best val accuracy : 0.6238
INFO flwr 2023-08-20 01:11:12,427 | common.py:35 | Avg. local train loss : 5.964086521416903, train acc : 0.68125
INFO flwr 2023-08-20 01:11:15,087 | server.py:116 | fit progress: (11, 1.1433113098144532, {'server_test_acc': 0.6175}, 959.3838049299084)
INFO flwr 2023-08-20 01:11:15,087 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-20 01:11:21,024 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3865661)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 01:11:52,862 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-20 01:11:53,008 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3865661)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3865665)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3865664)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3865667)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3865668)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3865666)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3865663)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3865662)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3865667)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3865664)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3865665)[0m malloc_consolidate(): invalid chunk size
E0820 01:11:53.933136804 3890946 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=3865663)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3865668)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3865662)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 01:12:40,019 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:12:40,020 | fed_df.py:547 | Average fusion training loss : 0.015322182070463895, val accuracy : 0.58328, best val accuracy : 0.5928
INFO flwr 2023-08-20 01:12:40,021 | common.py:35 | Avg. local train loss : 5.460049514472485, train acc : 0.7279111111111112
INFO flwr 2023-08-20 01:12:42,707 | server.py:116 | fit progress: (12, 1.2519452087402343, {'server_test_acc': 0.5798}, 1047.0036952951923)
INFO flwr 2023-08-20 01:12:42,707 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-20 01:12:48,668 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3932440)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 01:13:20,411 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-20 01:13:20,559 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3932442)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3932440)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3932437)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3932439)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3932443)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3932444)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3932441)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3932438)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3932437)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3932439)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3932443)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3932444)[0m double free or corruption (fasttop)
E0820 01:13:21.676551202 3891350 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
E0820 01:13:21.676687917 3891350 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=3932442)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3932441)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3932438)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 01:14:07,735 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:14:07,735 | fed_df.py:547 | Average fusion training loss : 0.012882811695337296, val accuracy : 0.55268, best val accuracy : 0.554
INFO flwr 2023-08-20 01:14:07,736 | common.py:35 | Avg. local train loss : 5.312292525172234, train acc : 0.7412055555555556
INFO flwr 2023-08-20 01:14:10,405 | server.py:116 | fit progress: (13, 1.4583637664794922, {'server_test_acc': 0.5445}, 1134.7019572481513)
INFO flwr 2023-08-20 01:14:10,405 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-20 01:14:16,288 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3999611)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3999612)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 01:14:48,072 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-20 01:14:48,217 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3999611)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3999614)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3999616)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3999617)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3999612)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3999609)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3999619)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3999618)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3999617)[0m double free or corruption (fasttop)
E0820 01:14:49.338252884 3958789 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=3999614)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3999616)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3999619)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3999609)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3999618)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 01:15:35,765 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:15:35,765 | fed_df.py:547 | Average fusion training loss : 0.017374754648655653, val accuracy : 0.58992, best val accuracy : 0.599
INFO flwr 2023-08-20 01:15:35,767 | common.py:35 | Avg. local train loss : 5.521044270694255, train acc : 0.7255499999999999
INFO flwr 2023-08-20 01:15:38,461 | server.py:116 | fit progress: (14, 1.2665427124023438, {'server_test_acc': 0.5961}, 1222.7576110018417)
INFO flwr 2023-08-20 01:15:38,461 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-20 01:15:44,435 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 01:16:15,618 | server.py:229 | fit_round 15 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=4066330)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 01:16:15,733 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-20 01:16:15,821 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4066330)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4066336)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4066337)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4066334)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4066338)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4066335)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4066339)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4066340)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4066337)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4066334)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4066340)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4066336)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4066335)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4066338)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4066339)[0m double free or corruption (fasttop)
E0820 01:16:19.222294821 4093201 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
INFO flwr 2023-08-20 01:17:02,729 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:17:02,729 | fed_df.py:547 | Average fusion training loss : 0.020587992276996373, val accuracy : 0.5851200000000001, best val accuracy : 0.5904
INFO flwr 2023-08-20 01:17:02,730 | common.py:35 | Avg. local train loss : 5.371147434413434, train acc : 0.7377777777777778
INFO flwr 2023-08-20 01:17:05,418 | server.py:116 | fit progress: (15, 1.339711474609375, {'server_test_acc': 0.5781}, 1309.715131783858)
INFO flwr 2023-08-20 01:17:05,419 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-20 01:17:11,383 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4133490)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4133492)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 01:17:42,616 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-20 01:17:42,760 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4133490)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4133495)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4133492)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4133498)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4133496)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4133493)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4133494)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4133497)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4133495)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4133498)[0m malloc_consolidate(): invalid chunk size
E0820 01:17:43.810002873 4159188 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=4133493)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4133494)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4133496)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4133497)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 01:18:29,963 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:18:29,964 | fed_df.py:547 | Average fusion training loss : 0.011510219868272543, val accuracy : 0.54888, best val accuracy : 0.563
INFO flwr 2023-08-20 01:18:29,965 | common.py:35 | Avg. local train loss : 5.333365700393916, train acc : 0.7414499999999998
INFO flwr 2023-08-20 01:18:32,631 | server.py:116 | fit progress: (16, 1.4376272521972657, {'server_test_acc': 0.5595}, 1396.9280154351145)
INFO flwr 2023-08-20 01:18:32,632 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-20 01:18:38,585 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=6494)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 01:19:09,916 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-20 01:19:10,062 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=6494)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=6497)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=6498)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=6496)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=6501)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=6499)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=6500)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=6495)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=6499)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=6495)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=6501)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=6498)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=6496)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=6500)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=6497)[0m malloc_consolidate(): invalid chunk size
E0820 01:19:12.190724002   34023 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
INFO flwr 2023-08-20 01:19:56,909 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:19:56,909 | fed_df.py:547 | Average fusion training loss : 0.012003749759867788, val accuracy : 0.59868, best val accuracy : 0.6046
INFO flwr 2023-08-20 01:19:56,910 | common.py:35 | Avg. local train loss : 5.464873259514571, train acc : 0.729588888888889
INFO flwr 2023-08-20 01:19:59,612 | server.py:116 | fit progress: (17, 1.2787661499023437, {'server_test_acc': 0.5897}, 1483.9084284272976)
INFO flwr 2023-08-20 01:19:59,612 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-20 01:20:05,534 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=74189)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=74181)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 01:20:37,208 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-20 01:20:37,355 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=74181)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=74182)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=74186)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=74187)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=74185)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=74184)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=74189)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=74188)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=74185)[0m malloc_consolidate(): invalid chunk size
E0820 01:20:37.780223792   99148 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=74186)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=74182)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=74188)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=74184)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=74187)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 01:21:24,484 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:21:24,484 | fed_df.py:547 | Average fusion training loss : 0.009871421778574587, val accuracy : 0.6014, best val accuracy : 0.632
INFO flwr 2023-08-20 01:21:24,485 | common.py:35 | Avg. local train loss : 5.24915871322155, train acc : 0.7530722222222223
INFO flwr 2023-08-20 01:21:27,179 | server.py:116 | fit progress: (18, 1.1398042266845703, {'server_test_acc': 0.6229}, 1571.4758301121183)
INFO flwr 2023-08-20 01:21:27,179 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-20 01:21:33,211 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=140915)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=140917)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=140919)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 01:22:04,743 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-20 01:22:04,890 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=140917)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=140915)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=140919)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=140924)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=140925)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=140922)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=140921)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=140923)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=140922)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=140925)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=140923)[0m malloc_consolidate(): invalid chunk size
E0820 01:22:05.796057029  166783 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 01:22:05.796187260  166783 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 01:22:05.796207281  166783 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 01:22:05.796219483  166783 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 01:22:05.796231961  166783 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=140921)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=140924)[0m malloc_consolidate(): invalid chunk size
E0820 01:22:06.845714930  166851 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 01:22:52,016 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:22:52,016 | fed_df.py:547 | Average fusion training loss : 0.01884162738546729, val accuracy : 0.60724, best val accuracy : 0.6292
INFO flwr 2023-08-20 01:22:52,017 | common.py:35 | Avg. local train loss : 5.263103532791137, train acc : 0.7509055555555556
INFO flwr 2023-08-20 01:22:54,710 | server.py:116 | fit progress: (19, 1.1395567108154296, {'server_test_acc': 0.6248}, 1659.0069929221645)
INFO flwr 2023-08-20 01:22:54,710 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-20 01:23:00,732 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=208518)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 01:23:32,434 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-20 01:23:32,548 | fed_df.py:365 | Warm start at round 20
[2m[36m(launch_and_fit pid=208522)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 01:23:32,652 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=208519)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=208518)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=208516)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=208521)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=208517)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=208520)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=208522)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=208523)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=208516)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=208517)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=208519)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=208520)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=208523)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=208521)[0m double free or corruption (fasttop)
E0820 01:23:37.725715645  254213 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 01:24:20,274 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:24:20,275 | fed_df.py:547 | Average fusion training loss : 0.019792296651750804, val accuracy : 0.63332, best val accuracy : 0.6454
INFO flwr 2023-08-20 01:24:20,276 | common.py:35 | Avg. local train loss : 5.520849961787462, train acc : 0.7261888888888889
INFO flwr 2023-08-20 01:24:22,985 | server.py:116 | fit progress: (20, 1.1360418762207032, {'server_test_acc': 0.6342}, 1747.2818371220492)
INFO flwr 2023-08-20 01:24:22,985 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-20 01:24:28,981 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=303554)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=303560)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 01:25:00,897 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-20 01:25:01,044 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=303554)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=303560)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=303563)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=303561)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=303558)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=303562)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=303557)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=303559)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=303563)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=303558)[0m double free or corruption (fasttop)
E0820 01:25:01.461254752  328747 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=303561)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=303557)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=303559)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=303562)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 01:25:53,617 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:25:53,618 | fed_df.py:547 | Average fusion training loss : 0.00994931205548346, val accuracy : 0.65296, best val accuracy : 0.6686
INFO flwr 2023-08-20 01:25:53,619 | common.py:35 | Avg. local train loss : 5.4069494441151615, train acc : 0.7389
INFO flwr 2023-08-20 01:25:56,257 | server.py:116 | fit progress: (21, 1.0457724884033204, {'server_test_acc': 0.6607}, 1840.5534384571947)
INFO flwr 2023-08-20 01:25:56,257 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-20 01:26:02,372 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 01:26:34,041 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-20 01:26:34,202 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=370501)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=370503)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=370499)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=370507)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=370504)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=370505)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=370506)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=370508)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=370508)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=370501)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=370504)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=370506)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=370499)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=370503)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=370505)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=370507)[0m double free or corruption (fasttop)
E0820 01:26:36.534513265  328848 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 01:27:21,983 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:27:21,983 | fed_df.py:547 | Average fusion training loss : 0.01851691774651408, val accuracy : 0.60584, best val accuracy : 0.6202
INFO flwr 2023-08-20 01:27:21,984 | common.py:35 | Avg. local train loss : 5.054939423501492, train acc : 0.7718388888888887
INFO flwr 2023-08-20 01:27:24,697 | server.py:116 | fit progress: (22, 1.2055103851318358, {'server_test_acc': 0.6145}, 1928.9935325332917)
INFO flwr 2023-08-20 01:27:24,697 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-20 01:27:30,764 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=437429)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 01:28:02,477 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-20 01:28:02,620 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=437429)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=437434)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=437431)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=437433)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=437432)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=437430)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=437436)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=437435)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=437436)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=437430)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=437434)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=437432)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=437433)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=437431)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=437435)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 01:28:55,264 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:28:55,264 | fed_df.py:547 | Average fusion training loss : 0.00903991473466158, val accuracy : 0.6408400000000001, best val accuracy : 0.6528
INFO flwr 2023-08-20 01:28:55,266 | common.py:35 | Avg. local train loss : 5.094946125149727, train acc : 0.7685555555555555
INFO flwr 2023-08-20 01:28:58,010 | server.py:116 | fit progress: (23, 1.1120567108154298, {'server_test_acc': 0.639}, 2022.3066992969252)
INFO flwr 2023-08-20 01:28:58,010 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-20 01:29:03,998 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=504444)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=504437)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=504440)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=504435)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 01:29:35,615 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-20 01:29:35,759 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=504442)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=504437)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=504435)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=504444)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=504440)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=504442)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=504443)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=504441)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=504439)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=504441)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=504439)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=504443)[0m malloc_consolidate(): invalid chunk size
E0820 01:29:39.468802812  530689 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 01:30:23,577 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:30:23,577 | fed_df.py:547 | Average fusion training loss : 0.010949922008439899, val accuracy : 0.6330399999999999, best val accuracy : 0.6426
INFO flwr 2023-08-20 01:30:23,578 | common.py:35 | Avg. local train loss : 5.386571815609932, train acc : 0.7414333333333334
INFO flwr 2023-08-20 01:30:26,326 | server.py:116 | fit progress: (24, 1.1276529663085937, {'server_test_acc': 0.6377}, 2110.6226616660133)
INFO flwr 2023-08-20 01:30:26,326 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-20 01:30:32,371 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 01:31:03,758 | server.py:229 | fit_round 25 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=571416)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 01:31:03,872 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-20 01:31:03,960 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=571416)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=571421)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=571417)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=571422)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=571423)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=571415)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=571419)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=571420)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=571420)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=571415)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=571422)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=571423)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=571417)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=571421)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=571419)[0m double free or corruption (fasttop)
E0820 01:31:06.935985861  598235 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 01:31:51,949 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:31:51,949 | fed_df.py:547 | Average fusion training loss : 0.019371412113308905, val accuracy : 0.6266, best val accuracy : 0.6314
INFO flwr 2023-08-20 01:31:51,950 | common.py:35 | Avg. local train loss : 5.162551776319742, train acc : 0.7607611111111112
INFO flwr 2023-08-20 01:31:54,652 | server.py:116 | fit progress: (25, 1.1858742736816406, {'server_test_acc': 0.6227}, 2198.9488182128407)
INFO flwr 2023-08-20 01:31:54,652 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-20 01:32:00,657 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 01:32:32,424 | server.py:229 | fit_round 26 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=638375)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 01:32:32,593 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=638378)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=638375)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=638377)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=638379)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=638374)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=638373)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=638376)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=638380)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=638378)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=638377)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=638376)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=638373)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=638379)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=638374)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=638380)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 01:33:20,654 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:33:20,655 | fed_df.py:547 | Average fusion training loss : 0.010935508592054248, val accuracy : 0.6806, best val accuracy : 0.6874
INFO flwr 2023-08-20 01:33:20,656 | common.py:35 | Avg. local train loss : 5.327468118071556, train acc : 0.7462611111111112
INFO flwr 2023-08-20 01:33:23,395 | server.py:116 | fit progress: (26, 1.001185055541992, {'server_test_acc': 0.6708}, 2287.6916793580167)
INFO flwr 2023-08-20 01:33:23,395 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-20 01:33:29,459 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 01:34:00,947 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-20 01:34:01,092 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=705307)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=705308)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=705303)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=705306)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=705305)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=705304)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=705310)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=705309)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=705303)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=705310)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=705308)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=705307)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=705305)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=705306)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=705304)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=705309)[0m malloc_consolidate(): invalid chunk size
E0820 01:34:05.023861894  731832 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 01:34:49,283 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:34:49,284 | fed_df.py:547 | Average fusion training loss : 0.013382589044049382, val accuracy : 0.65412, best val accuracy : 0.664
INFO flwr 2023-08-20 01:34:49,284 | common.py:35 | Avg. local train loss : 5.087236922234297, train acc : 0.7702333333333333
INFO flwr 2023-08-20 01:34:52,015 | server.py:116 | fit progress: (27, 1.0859396087646485, {'server_test_acc': 0.6476}, 2376.3116843001917)
INFO flwr 2023-08-20 01:34:52,015 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-20 01:34:57,960 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=772055)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 01:35:29,492 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-20 01:35:29,638 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=772053)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=772050)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=772048)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=772054)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=772057)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=772055)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=772056)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=772058)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=772053)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=772058)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=772054)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=772048)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=772050)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=772056)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=772057)[0m malloc_consolidate(): invalid chunk size
E0820 01:35:33.123073523  798969 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 01:36:17,751 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:36:17,752 | fed_df.py:547 | Average fusion training loss : 0.010745270142331719, val accuracy : 0.64304, best val accuracy : 0.6566
INFO flwr 2023-08-20 01:36:17,753 | common.py:35 | Avg. local train loss : 5.229855775833131, train acc : 0.7572166666666666
INFO flwr 2023-08-20 01:36:20,475 | server.py:116 | fit progress: (28, 1.1058424285888673, {'server_test_acc': 0.6417}, 2464.7715263250284)
INFO flwr 2023-08-20 01:36:20,475 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-20 01:36:26,502 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 01:36:58,072 | server.py:229 | fit_round 29 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=839178)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 01:36:58,219 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=839182)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=839178)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=839184)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=839183)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=839185)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=839186)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=839180)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=839181)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=839183)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=839186)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=839185)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=839181)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=839182)[0m double free or corruption (fasttop)
E0820 01:36:59.642769645  865277 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=839184)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=839180)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 01:37:45,725 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:37:45,725 | fed_df.py:547 | Average fusion training loss : 0.009318224161863327, val accuracy : 0.6373200000000001, best val accuracy : 0.6428
INFO flwr 2023-08-20 01:37:45,726 | common.py:35 | Avg. local train loss : 5.1491271667182446, train acc : 0.7667666666666667
INFO flwr 2023-08-20 01:37:48,450 | server.py:116 | fit progress: (29, 1.1844864624023437, {'server_test_acc': 0.6331}, 2552.746566785034)
INFO flwr 2023-08-20 01:37:48,450 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-20 01:37:54,480 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=905879)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 01:38:25,950 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-20 01:38:26,066 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-20 01:38:26,179 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=905877)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=905882)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=905879)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=905885)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=905880)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=905884)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=905883)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=905881)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=905883)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=905885)[0m malloc_consolidate(): invalid chunk size
E0820 01:38:27.399819534  940275 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=905882)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=905884)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=905880)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=905881)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=905877)[0m double free or corruption (fasttop)
E0820 01:38:28.755539949  943806 chttp2_transport.cc:1079]             ipv4:145.136.62.22:43858: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 01:39:14,302 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 01:39:14,302 | fed_df.py:547 | Average fusion training loss : 0.02090997890383005, val accuracy : 0.5996, best val accuracy : 0.6092
INFO flwr 2023-08-20 01:39:14,303 | common.py:35 | Avg. local train loss : 4.731525141745806, train acc : 0.8045722222222222
INFO flwr 2023-08-20 01:39:17,039 | server.py:116 | fit progress: (30, 1.2925338623046876, {'server_test_acc': 0.5996}, 2641.3360831588507)
INFO flwr 2023-08-20 01:39:17,040 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-20 01:39:17,040 | server.py:144 | FL finished in 2641.336451953277
INFO flwr 2023-08-20 01:39:17,040 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-20 01:39:17,041 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-20 01:39:17,041 | app.py:204 | app_fit: losses_centralized [(0, 2.319245477294922), (1, 1.9777800048828125), (2, 1.9165531799316406), (3, 1.5061278533935547), (4, 1.3947014099121093), (5, 1.6327973175048829), (6, 1.55310673828125), (7, 1.4775602783203126), (8, 1.300870004272461), (9, 1.3594434020996093), (10, 1.1737774047851564), (11, 1.1433113098144532), (12, 1.2519452087402343), (13, 1.4583637664794922), (14, 1.2665427124023438), (15, 1.339711474609375), (16, 1.4376272521972657), (17, 1.2787661499023437), (18, 1.1398042266845703), (19, 1.1395567108154296), (20, 1.1360418762207032), (21, 1.0457724884033204), (22, 1.2055103851318358), (23, 1.1120567108154298), (24, 1.1276529663085937), (25, 1.1858742736816406), (26, 1.001185055541992), (27, 1.0859396087646485), (28, 1.1058424285888673), (29, 1.1844864624023437), (30, 1.2925338623046876)]
INFO flwr 2023-08-20 01:39:17,041 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0811), (1, 0.3132), (2, 0.3564), (3, 0.4555), (4, 0.5044), (5, 0.4665), (6, 0.4845), (7, 0.5182), (8, 0.566), (9, 0.5636), (10, 0.6064), (11, 0.6175), (12, 0.5798), (13, 0.5445), (14, 0.5961), (15, 0.5781), (16, 0.5595), (17, 0.5897), (18, 0.6229), (19, 0.6248), (20, 0.6342), (21, 0.6607), (22, 0.6145), (23, 0.639), (24, 0.6377), (25, 0.6227), (26, 0.6708), (27, 0.6476), (28, 0.6417), (29, 0.6331), (30, 0.5996)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn22: task 0: Aborted
srun: Terminating StepId=3425001.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3425001
Cluster: snellius
User/Group: sunnys/sunnys
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 01:57:10
CPU Efficiency: 13.80% of 14:09:00 core-walltime
Job Wall-clock time: 00:47:10
Memory Utilized: 48.74 GB
Memory Efficiency: 40.62% of 120.00 GB
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
